package git

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pkuehne/dots/internal/config"
	"github.com/pkuehne/dots/internal/shell"
)

func TestGenerateConfig_Header(t *testing.T) {
	cfg := config.Config{}
	cfg.Git.DefaultBranch = "main"
	result := GenerateConfig(cfg)
	if !strings.Contains(result, "Generated by dots") {
		t.Error("expected generated header")
	}
}

func TestGenerateConfig_User(t *testing.T) {
	cfg := config.Config{}
	cfg.Git.Name = "Test User"
	cfg.Git.Email = "test@example.com"
	cfg.Git.DefaultBranch = "main"
	result := GenerateConfig(cfg)
	if !strings.Contains(result, "[user]") {
		t.Error("expected [user] section")
	}
	if !strings.Contains(result, "name = Test User") {
		t.Error("expected name")
	}
	if !strings.Contains(result, "email = test@example.com") {
		t.Error("expected email")
	}
}

func TestGenerateConfig_Editor(t *testing.T) {
	cfg := config.Config{}
	cfg.Git.Editor = "nvim"
	cfg.Git.DefaultBranch = "main"
	result := GenerateConfig(cfg)
	if !strings.Contains(result, "[core]") {
		t.Error("expected [core] section")
	}
	if !strings.Contains(result, "editor = nvim") {
		t.Error("expected editor")
	}
}

func TestGenerateConfig_DefaultBranch(t *testing.T) {
	cfg := config.Config{}
	cfg.Git.DefaultBranch = "trunk"
	result := GenerateConfig(cfg)
	if !strings.Contains(result, "defaultBranch = trunk") {
		t.Error("expected defaultBranch")
	}
}

func TestGenerateConfig_PullRebase(t *testing.T) {
	cfg := config.Config{}
	cfg.Git.PullRebase = true
	cfg.Git.DefaultBranch = "main"
	result := GenerateConfig(cfg)
	if !strings.Contains(result, "rebase = true") {
		t.Error("expected rebase = true")
	}
}

func TestGenerateConfig_PullNoRebase(t *testing.T) {
	cfg := config.Config{}
	cfg.Git.PullRebase = false
	cfg.Git.DefaultBranch = "main"
	result := GenerateConfig(cfg)
	if !strings.Contains(result, "rebase = false") {
		t.Error("expected rebase = false")
	}
}

func TestGenerateConfig_Signing(t *testing.T) {
	cfg := config.Config{}
	cfg.Git.Name = "Test"
	cfg.Git.Email = "test@example.com"
	cfg.Git.Sign = true
	cfg.Git.SigningKey = "ABCD1234"
	cfg.Git.DefaultBranch = "main"
	result := GenerateConfig(cfg)
	if !strings.Contains(result, "[commit]") {
		t.Error("expected [commit] section")
	}
	if !strings.Contains(result, "gpgsign = true") {
		t.Error("expected gpgsign = true")
	}
	if !strings.Contains(result, "signingkey = ABCD1234") {
		t.Error("expected signingkey")
	}
}

func TestGenerateConfig_DeltaOmittedWhenMissing(t *testing.T) {
	// Skip if delta happens to be installed — we can't control exec.LookPath.
	if _, err := exec.LookPath("delta"); err == nil {
		t.Skip("delta is installed; cannot test absent-delta path")
	}
	tool := config.Tool{Name: "delta"}
	tool.Git.Pager = true
	tool.Git.Diff = true
	cfg := config.Config{}
	cfg.Git.DefaultBranch = "main"
	cfg.Tools = []config.Tool{tool}
	result := GenerateConfig(cfg)
	if strings.Contains(result, "pager = delta") {
		t.Error("expected delta pager to be absent when delta not installed")
	}
	if strings.Contains(result, "[diff]") {
		t.Error("expected [diff] to be absent when delta not installed")
	}
}

func TestGenerateConfig_DeltaWhenInstalled(t *testing.T) {
	if _, err := exec.LookPath("delta"); err != nil {
		t.Skip("delta not installed; skipping delta-present test")
	}
	tool := config.Tool{Name: "delta"}
	tool.Git.Pager = true
	tool.Git.Diff = true
	cfg := config.Config{}
	cfg.Git.DefaultBranch = "main"
	cfg.Tools = []config.Tool{tool}
	result := GenerateConfig(cfg)
	if !strings.Contains(result, "pager = delta") {
		t.Error("expected pager = delta")
	}
	if !strings.Contains(result, "[diff]") {
		t.Error("expected [diff] section")
	}
	if !strings.Contains(result, "tool = delta") {
		t.Error("expected tool = delta")
	}
}

func TestWriteManaged_DryRun(t *testing.T) {
	cfg := config.Config{}
	cfg.Git.DefaultBranch = "main"
	// Dry run should not create any files.
	t.Setenv("HOME", t.TempDir())
	if err := WriteManaged(cfg, true, false, nil); err != nil {
		t.Fatalf("WriteManaged dry-run: %v", err)
	}
}

func TestWriteManaged_CreatesFile(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	cfg.Git.Name = "Alice"
	cfg.Git.DefaultBranch = "main"

	if err := WriteManaged(cfg, false, false, nil); err != nil {
		t.Fatalf("WriteManaged: %v", err)
	}

	outPath := filepath.Join(home, ".config", "dots", "git", "managed.gitconfig")
	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("reading managed.gitconfig: %v", err)
	}
	if !strings.Contains(string(data), "name = Alice") {
		t.Error("managed.gitconfig missing name")
	}
}

func TestWriteManaged_InsertsIncludeBlock(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	cfg.Git.DefaultBranch = "main"

	if err := WriteManaged(cfg, false, false, nil); err != nil {
		t.Fatalf("WriteManaged: %v", err)
	}

	gitconfig := filepath.Join(home, ".gitconfig")
	data, err := os.ReadFile(gitconfig)
	if err != nil {
		t.Fatalf("reading ~/.gitconfig: %v", err)
	}
	if !strings.Contains(string(data), shell.MarkerStart) {
		t.Error("~/.gitconfig missing marker block")
	}
	if !strings.Contains(string(data), "managed.gitconfig") {
		t.Error("~/.gitconfig missing include path")
	}
}

func TestWriteManaged_Idempotent(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	cfg.Git.DefaultBranch = "main"

	if err := WriteManaged(cfg, false, false, nil); err != nil {
		t.Fatalf("first WriteManaged: %v", err)
	}
	if err := WriteManaged(cfg, false, false, nil); err != nil {
		t.Fatalf("second WriteManaged: %v", err)
	}

	gitconfig := filepath.Join(home, ".gitconfig")
	data, err := os.ReadFile(gitconfig)
	if err != nil {
		t.Fatal(err)
	}
	// Marker should appear exactly once.
	count := strings.Count(string(data), shell.MarkerStart)
	if count != 1 {
		t.Errorf("expected 1 marker block, got %d", count)
	}
}

func TestUninit_RemovesBlock(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	cfg.Git.DefaultBranch = "main"

	if err := WriteManaged(cfg, false, false, nil); err != nil {
		t.Fatalf("WriteManaged: %v", err)
	}
	if err := Uninit(cfg, false); err != nil {
		t.Fatalf("Uninit: %v", err)
	}

	gitconfig := filepath.Join(home, ".gitconfig")
	data, err := os.ReadFile(gitconfig)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), shell.MarkerStart) {
		t.Error("expected marker block to be removed")
	}
}

func TestUninit_DryRun(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	cfg.Git.DefaultBranch = "main"

	if err := WriteManaged(cfg, false, false, nil); err != nil {
		t.Fatal(err)
	}
	if err := Uninit(cfg, true); err != nil {
		t.Fatalf("Uninit dry-run: %v", err)
	}

	gitconfig := filepath.Join(home, ".gitconfig")
	data, _ := os.ReadFile(gitconfig)
	if !strings.Contains(string(data), shell.MarkerStart) {
		t.Error("dry-run uninit must not modify the file")
	}
}
