"""Constants used across the dots package."""

VERSION = "0.1.0"
MARKER_START = "# >>> dots managed — do not edit between these markers >>>"
MARKER_END = "# <<< dots managed <<<"
GENERATED_HEADER = "# Generated by dots — do not edit directly."
SKIP_NAMES = {".git", ".DS_Store"}
SKIP_SUFFIXES = {".swp"}
SKIP_PATTERNS = {"*~"}

SENSITIVE_DIRS = {
    ".ssh": 0o700,
    ".gnupg": 0o700,
}

SSH_KEYWORD_MAP = {
    "host": "Host",
    "hostname": "HostName",
    "user": "User",
    "port": "Port",
    "identity_file": "IdentityFile",
    "forward_agent": "ForwardAgent",
    "proxy_jump": "ProxyJump",
    "proxy_command": "ProxyCommand",
    "strict_host_key_checking": "StrictHostKeyChecking",
    "user_known_hosts_file": "UserKnownHostsFile",
    "server_alive_interval": "ServerAliveInterval",
    "server_alive_count_max": "ServerAliveCountMax",
    "compression": "Compression",
    "log_level": "LogLevel",
    "local_forward": "LocalForward",
    "remote_forward": "RemoteForward",
    "dynamic_forward": "DynamicForward",
    "request_tty": "RequestTTY",
    "add_keys_to_agent": "AddKeysToAgent",
    "identities_only": "IdentitiesOnly",
    "certificate_file": "CertificateFile",
    "preferred_authentications": "PreferredAuthentications",
    "pubkey_accepted_algorithms": "PubkeyAcceptedAlgorithms",
    "connect_timeout": "ConnectTimeout",
}
