"""Preset generation and login shell file generation."""

from __future__ import annotations

from dots.config import Config
from dots.constants import GENERATED_HEADER
from dots.utils import expand


def generate_fzf_preset(shell_name: str = "zsh") -> str:
    lines = [
        GENERATED_HEADER.replace("dots", "dots preset: fzf"),
        "# To customise: dots presets eject fzf",
        "",
        "command -v fzf >/dev/null 2>&1 || return",
        "",
        'export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border --cycle"',
        "",
        "# Use rg for file listing if available",
        "command -v rg >/dev/null 2>&1 && \\",
        "    export FZF_DEFAULT_COMMAND=\"rg --files --hidden --glob '!.git'\"",
        "",
        "# Shell key bindings — location varies by install method",
        "for _fzf_f in \\",
        f"    /usr/share/doc/fzf/examples/key-bindings.{shell_name}.sh \\",
        f"    /usr/share/fzf/key-bindings.{shell_name}.sh \\",
        f"    ~/.fzf.{shell_name}; do",
        '    [ -f "$_fzf_f" ] && source "$_fzf_f" && break',
        "done",
        "unset _fzf_f",
    ]
    return "\n".join(lines) + "\n"


TMUX_PRESET = """\
# Generated by dots preset: tmux — do not edit directly.
# To customise: dots presets eject tmux

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Plugins (managed by tpm)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize tpm (must be last line)
run '~/.tmux/plugins/tpm/tpm'
"""


# ── Login Shell Files ────────────────────────────────────────────────────────


def generate_zprofile(config: Config) -> str:
    lines = [
        GENERATED_HEADER,
        "# Source: dots.toml [env] + [shell] path",
        "# Regenerate: dots apply",
        "# Login shell only: PATH and env, no interactive features.",
        "",
    ]
    # Env
    for key, value in sorted(config.env.items()):
        lines.append(f'export {key}="{value}"')
    lines.append("")
    # Path
    paths = list(config.shell.path)
    for tool in config.tools:
        for p in tool.shell.path:
            if p not in paths:
                paths.append(p)
    if config.tools:
        bin_dir = config.tools_config.bin_dir
        if bin_dir not in paths:
            paths.insert(0, bin_dir)
    for p in paths:
        expanded = expand(p)
        lines.append(
            f'case ":$PATH:" in *":{expanded}:"*) ;; *) export PATH="{expanded}:$PATH" ;; esac'
        )
    return "\n".join(lines) + "\n"


def generate_profile(config: Config) -> str:
    # POSIX sh compatible version
    return generate_zprofile(config)
