// Package lockfile records which versions of [[tool]] entries dots has
// installed on this machine. It is the source of truth for version tracking:
// `tools status` compares the recorded version against the configured target,
// and `tools update` reinstalls when they differ.
//
// The lockfile is machine-local state — it describes what is installed here,
// not what the dotfiles repo declares — so it lives under ~/.config/dots rather
// than in the repo. Only versions dots itself installs (the github method) are
// recorded; package-manager installs (apt, brew, …) are tracked by their own
// managers.
package lockfile

import (
	"bytes"
	"os"
	"sort"
	"sync"
	"time"

	"github.com/BurntSushi/toml"
	"github.com/pkuehne/dots/internal/errs"
	"github.com/pkuehne/dots/internal/fileutil"
)

// DefaultPath is where the lockfile lives when no override is given.
const DefaultPath = "~/.config/dots/installed.toml"

const header = "# Generated by dots — records installed tool versions for `dots tools status`\n" +
	"# and `dots tools update`. Machine-local state; do not edit or commit.\n\n"

// Entry is one recorded tool installation. Only the github install method
// records entries, so the method is implicit and not stored.
type Entry struct {
	Version   string `toml:"version"`   // version installed (tag without leading v)
	Installed string `toml:"installed"` // date recorded, YYYY-MM-DD
}

// Lock is the parsed lockfile plus the path it was loaded from. Each tool is a
// top-level [<name>] table in the file. The mutex makes Get/Set/Remove/Save
// safe to call concurrently, so a parallel batch of installs (`tools update`)
// can record versions into one shared Lock.
type Lock struct {
	path  string
	mu    sync.Mutex
	Tools map[string]Entry
}

// Load reads the lockfile at path (DefaultPath when empty). A missing file is
// not an error — it yields an empty lock ready to be populated and saved.
func Load(path string) (*Lock, error) {
	if path == "" {
		path = DefaultPath
	}
	p := fileutil.Expand(path)
	l := &Lock{path: p, Tools: map[string]Entry{}}

	data, err := os.ReadFile(p)
	if os.IsNotExist(err) {
		return l, nil
	}
	if err != nil {
		return nil, errs.NewTool("cannot read lockfile "+p, err.Error())
	}
	if err := toml.Unmarshal(data, &l.Tools); err != nil {
		return nil, errs.NewTool("cannot parse lockfile "+p,
			"The lockfile is corrupt. Delete it to let dots rebuild it:\n  rm "+p)
	}
	if l.Tools == nil {
		l.Tools = map[string]Entry{}
	}
	return l, nil
}

// Get returns the recorded entry for name and whether it was present.
func (l *Lock) Get(name string) (Entry, bool) {
	l.mu.Lock()
	defer l.mu.Unlock()
	e, ok := l.Tools[name]
	return e, ok
}

// Set records an installation. Installed defaults to today (UTC) when empty.
func (l *Lock) Set(name string, e Entry) {
	if e.Installed == "" {
		e.Installed = time.Now().UTC().Format("2006-01-02")
	}
	l.mu.Lock()
	defer l.mu.Unlock()
	l.Tools[name] = e
}

// Remove deletes a recorded entry. It is a no-op when absent.
func (l *Lock) Remove(name string) {
	l.mu.Lock()
	defer l.mu.Unlock()
	delete(l.Tools, name)
}

// Save writes the lockfile back to disk, creating the parent directory. Each
// tool is rendered as a top-level [<name>] table with version and installed
// keys. The library encoder emits map keys in sorted order, so the file is
// stable across runs.
func (l *Lock) Save() error {
	if err := fileutil.EnsureParent(l.path); err != nil {
		return errs.NewTool("cannot create lockfile directory", err.Error())
	}

	l.mu.Lock()
	defer l.mu.Unlock()

	var buf bytes.Buffer
	buf.WriteString(header)
	if len(l.Tools) > 0 {
		enc := toml.NewEncoder(&buf)
		enc.Indent = "" // keep table keys flush at column 0
		if err := enc.Encode(l.Tools); err != nil {
			return errs.NewTool("cannot encode lockfile", err.Error())
		}
	}

	if err := os.WriteFile(l.path, buf.Bytes(), 0o644); err != nil {
		return errs.NewTool("cannot write lockfile "+l.path, err.Error())
	}
	return nil
}

// Names returns the recorded tool names in sorted order.
func (l *Lock) Names() []string {
	l.mu.Lock()
	defer l.mu.Unlock()
	names := make([]string, 0, len(l.Tools))
	for n := range l.Tools {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}
