package lockfile

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLoad_Missing(t *testing.T) {
	path := filepath.Join(t.TempDir(), "installed.toml")
	l, err := Load(path)
	if err != nil {
		t.Fatalf("Load missing: %v", err)
	}
	if len(l.Tools) != 0 {
		t.Fatalf("want empty lock, got %d entries", len(l.Tools))
	}
}

func TestSetSaveLoad_RoundTrip(t *testing.T) {
	path := filepath.Join(t.TempDir(), "installed.toml")
	l, err := Load(path)
	if err != nil {
		t.Fatal(err)
	}
	l.Set("lazygit", Entry{Version: "0.44.1"})
	l.Set("fzf", Entry{Version: "0.55.0", Installed: "2026-01-01"})
	if err := l.Save(); err != nil {
		t.Fatalf("Save: %v", err)
	}

	got, err := Load(path)
	if err != nil {
		t.Fatalf("reload: %v", err)
	}
	e, ok := got.Get("lazygit")
	if !ok {
		t.Fatal("lazygit missing after reload")
	}
	if e.Version != "0.44.1" {
		t.Errorf("unexpected entry: %+v", e)
	}
	if e.Installed == "" {
		t.Error("Installed should be defaulted to today")
	}
	if e, _ := got.Get("fzf"); e.Installed != "2026-01-01" {
		t.Errorf("explicit Installed not preserved: %q", e.Installed)
	}
}

func TestSave_WritesHeader(t *testing.T) {
	path := filepath.Join(t.TempDir(), "installed.toml")
	l, _ := Load(path)
	l.Set("rg", Entry{Version: "14.0.0"})
	if err := l.Save(); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(data), "# Generated by dots") {
		t.Errorf("lockfile missing generated header:\n%s", data)
	}
}

func TestSave_TableFormat(t *testing.T) {
	path := filepath.Join(t.TempDir(), "installed.toml")
	l, _ := Load(path)
	l.Set("lazygit", Entry{Version: "0.44.1", Installed: "2026-06-24"})
	l.Set("fzf", Entry{Version: "0.55.0", Installed: "2026-06-24"})
	if err := l.Save(); err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(path)
	got := string(data)

	// One top-level [<name>] table per tool, version + installed keys, sorted.
	for _, want := range []string{
		"[fzf]\n",
		"version = \"0.55.0\"\n",
		"installed = \"2026-06-24\"\n",
		"[lazygit]\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("missing %q in:\n%s", want, got)
		}
	}
	if strings.Index(got, "[fzf]") > strings.Index(got, "[lazygit]") {
		t.Error("entries not sorted by name")
	}
}

func TestSave_QuotesUnsafeNames(t *testing.T) {
	path := filepath.Join(t.TempDir(), "installed.toml")
	l, _ := Load(path)
	l.Set("weird name.v2", Entry{Version: "1.0.0", Installed: "2026-06-24"})
	if err := l.Save(); err != nil {
		t.Fatal(err)
	}
	got, err := Load(path)
	if err != nil {
		t.Fatalf("reload with unsafe key: %v", err)
	}
	if e, ok := got.Get("weird name.v2"); !ok || e.Version != "1.0.0" {
		t.Errorf("unsafe-named entry not round-tripped: %+v ok=%v", e, ok)
	}
}

func TestRemove(t *testing.T) {
	l, _ := Load(filepath.Join(t.TempDir(), "installed.toml"))
	l.Set("a", Entry{Version: "1"})
	l.Remove("a")
	if _, ok := l.Get("a"); ok {
		t.Error("entry still present after Remove")
	}
	l.Remove("missing") // no-op, must not panic
}

func TestNames_Sorted(t *testing.T) {
	l, _ := Load(filepath.Join(t.TempDir(), "installed.toml"))
	l.Set("zebra", Entry{Version: "1"})
	l.Set("alpha", Entry{Version: "1"})
	names := l.Names()
	if len(names) != 2 || names[0] != "alpha" || names[1] != "zebra" {
		t.Errorf("Names() = %v, want sorted [alpha zebra]", names)
	}
}

func TestLoad_Corrupt(t *testing.T) {
	path := filepath.Join(t.TempDir(), "installed.toml")
	if err := os.WriteFile(path, []byte("this is = = not valid toml ]["), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Load(path); err == nil {
		t.Fatal("expected error for corrupt lockfile")
	}
}
