// Package presets generates opinionated config snippets for named presets (fzf, tmux)
// and login-shell profile files (zprofile/profile).
package presets

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/pkuehne/dots/internal/config"
	"github.com/pkuehne/dots/internal/errs"
	"github.com/pkuehne/dots/internal/fileutil"
	"github.com/pkuehne/dots/internal/shell"
)

// fzfHeader is the generated-file header for the fzf preset.
const fzfHeader = "# Generated by dots preset: fzf — do not edit directly."

// GenerateFzf returns the fzf shell snippet for the given shell name (e.g. "zsh").
func GenerateFzf(shellName string) string {
	lines := []string{
		fzfHeader,
		"# To customise: dots presets eject fzf",
		"",
		"command -v fzf >/dev/null 2>&1 || return",
		"",
		`export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border --cycle"`,
		"",
		"# Use rg for file listing if available",
		`command -v rg >/dev/null 2>&1 && \`,
		`    export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git'"`,
		"",
		"# Shell key bindings — location varies by install method",
		`for _fzf_f in \`,
		fmt.Sprintf(`    /usr/share/doc/fzf/examples/key-bindings.%s.sh \`, shellName),
		fmt.Sprintf(`    /usr/share/fzf/key-bindings.%s.sh \`, shellName),
		fmt.Sprintf(`    ~/.fzf.%s; do`, shellName),
		`    [ -f "$_fzf_f" ] && source "$_fzf_f" && break`,
		"done",
		"unset _fzf_f",
	}
	return strings.Join(lines, "\n") + "\n"
}

// TmuxPreset is the verbatim tmux preset content.
const TmuxPreset = `# Generated by dots preset: tmux — do not edit directly.
# To customise: dots presets eject tmux

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Plugins (managed by tpm)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize tpm (must be last line)
run '~/.tmux/plugins/tpm/tpm'
`

// Generate returns the generated content for a named preset.
func Generate(name string, cfg config.Config) (string, error) {
	switch name {
	case "fzf":
		return GenerateFzf("zsh"), nil
	case "tmux":
		return TmuxPreset, nil
	default:
		return "", errs.New("unknown preset: "+name, "Available presets: "+strings.Join(Available(), ", "))
	}
}

// Eject writes a preset's generated content to dest as a plain file.
// After ejection the preset flag should be removed from dots.toml.
func Eject(name, dest string, cfg config.Config) error {
	content, err := Generate(name, cfg)
	if err != nil {
		return err
	}
	if err := fileutil.EnsureParent(dest); err != nil {
		return errs.New("cannot create parent directory for "+dest, err.Error())
	}
	if err := os.WriteFile(dest, []byte(content), 0o644); err != nil {
		return errs.New("cannot write preset file: "+dest, err.Error())
	}
	return nil
}

// Available returns the list of known preset names.
func Available() []string {
	return []string{"fzf", "tmux"}
}

// GenerateZprofile generates the content of ~/.zprofile (or ~/.profile) from
// cfg. It exports [env] vars and prepends [shell] path + tool paths to PATH.
// This is the login-shell file: PATH and env only, no interactive features.
func GenerateZprofile(cfg config.Config) string {
	lines := []string{
		shell.GeneratedHeader,
		"# Source: dots.toml [env] + [shell] path",
		"# Regenerate: dots apply",
		"# Login shell only: PATH and env, no interactive features.",
		"",
	}

	// Env vars in sorted order.
	keys := make([]string, 0, len(cfg.Env.Vars))
	for k := range cfg.Env.Vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		lines = append(lines, fmt.Sprintf(`export %s="%s"`, k, cfg.Env.Vars[k]))
	}
	lines = append(lines, "")

	// Build path list: shell.path + per-tool shell.path (deduplicated), then
	// prepend bin_dir if any tools are configured.
	seen := map[string]bool{}
	paths := []string{}
	for _, p := range cfg.Shell.Path {
		if !seen[p] {
			seen[p] = true
			paths = append(paths, p)
		}
	}
	for _, t := range cfg.Tools {
		for _, p := range t.Shell.Path {
			if !seen[p] {
				seen[p] = true
				paths = append(paths, p)
			}
		}
	}
	if len(cfg.Tools) > 0 {
		binDir := cfg.ToolsConfig.BinDir
		if !seen[binDir] {
			paths = append([]string{binDir}, paths...)
		}
	}

	for _, p := range paths {
		expanded := fileutil.Expand(p)
		lines = append(lines, fmt.Sprintf(
			`case ":$PATH:" in *":%s:"*) ;; *) export PATH="%s:$PATH" ;; esac`,
			expanded, expanded,
		))
	}

	return strings.Join(lines, "\n") + "\n"
}

// GenerateProfile generates POSIX sh profile content; identical to zprofile.
func GenerateProfile(cfg config.Config) string {
	return GenerateZprofile(cfg)
}
