package presets_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pkuehne/dots/internal/config"
	"github.com/pkuehne/dots/internal/presets"
)

// ── GenerateFzf ───────────────────────────────────────────────────────────────

func TestGenerateFzf_DefaultShell(t *testing.T) {
	out := presets.GenerateFzf("zsh")

	// Must start with the preset header.
	if !strings.HasPrefix(out, "# Generated by dots preset: fzf") {
		t.Fatalf("missing fzf header, got: %q", out[:50])
	}
	// Must contain the customise comment.
	if !strings.Contains(out, "dots presets eject fzf") {
		t.Error("missing eject hint")
	}
	// Must check for fzf binary.
	if !strings.Contains(out, "command -v fzf") {
		t.Error("missing fzf guard")
	}
	// Shell-specific key-binding paths.
	if !strings.Contains(out, "key-bindings.zsh.sh") {
		t.Error("missing zsh key-binding path")
	}
	if !strings.Contains(out, ".fzf.zsh") {
		t.Error("missing ~/.fzf.zsh path")
	}
	// Must end with newline.
	if !strings.HasSuffix(out, "\n") {
		t.Error("output should end with newline")
	}
}

func TestGenerateFzf_BashShell(t *testing.T) {
	out := presets.GenerateFzf("bash")
	if !strings.Contains(out, "key-bindings.bash.sh") {
		t.Error("missing bash key-binding path")
	}
	if !strings.Contains(out, ".fzf.bash") {
		t.Error("missing ~/.fzf.bash path")
	}
	// Must not have zsh-specific paths.
	if strings.Contains(out, ".fzf.zsh") {
		t.Error("unexpected zsh path in bash output")
	}
}

// ── TmuxPreset ────────────────────────────────────────────────────────────────

func TestTmuxPreset_Content(t *testing.T) {
	out := presets.TmuxPreset
	checks := []string{
		"# Generated by dots preset: tmux",
		"dots presets eject tmux",
		"set -g prefix C-a",
		"set -g mouse on",
		"tmux-256color",
		"tmux-plugins/tpm",
		"run '~/.tmux/plugins/tpm/tpm'",
	}
	for _, want := range checks {
		if !strings.Contains(out, want) {
			t.Errorf("TmuxPreset missing %q", want)
		}
	}
	if !strings.HasSuffix(out, "\n") {
		t.Error("TmuxPreset should end with newline")
	}
}

// ── Generate ──────────────────────────────────────────────────────────────────

func TestGenerate_Fzf(t *testing.T) {
	out, err := presets.Generate("fzf", config.Config{})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "command -v fzf") {
		t.Error("fzf preset missing binary guard")
	}
}

func TestGenerate_Tmux(t *testing.T) {
	out, err := presets.Generate("tmux", config.Config{})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out, "set -g prefix C-a") {
		t.Error("tmux preset missing prefix config")
	}
}

func TestGenerate_Unknown(t *testing.T) {
	_, err := presets.Generate("nope", config.Config{})
	if err == nil {
		t.Fatal("expected error for unknown preset")
	}
	if !strings.Contains(err.Error(), "unknown preset") {
		t.Errorf("unexpected error message: %v", err)
	}
}

// ── Available ─────────────────────────────────────────────────────────────────

func TestAvailable(t *testing.T) {
	got := presets.Available()
	want := map[string]bool{"fzf": true, "tmux": true}
	if len(got) != len(want) {
		t.Fatalf("Available() = %v, want %v presets", got, len(want))
	}
	for _, name := range got {
		if !want[name] {
			t.Errorf("unexpected preset name: %q", name)
		}
	}
}

// ── Eject ─────────────────────────────────────────────────────────────────────

func TestEject_WritesFzfPreset(t *testing.T) {
	dir := t.TempDir()
	dest := filepath.Join(dir, "subdir", "fzf.zsh")
	if err := presets.Eject("fzf", dest, config.Config{}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(dest)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "command -v fzf") {
		t.Error("ejected file missing fzf content")
	}
}

func TestEject_WritesTmuxPreset(t *testing.T) {
	dir := t.TempDir()
	dest := filepath.Join(dir, ".tmux.conf")
	if err := presets.Eject("tmux", dest, config.Config{}); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(dest)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "set -g prefix C-a") {
		t.Error("ejected file missing tmux content")
	}
}

func TestEject_UnknownPreset(t *testing.T) {
	dir := t.TempDir()
	err := presets.Eject("nope", filepath.Join(dir, "out"), config.Config{})
	if err == nil {
		t.Fatal("expected error for unknown preset")
	}
}

// ── GenerateZprofile ──────────────────────────────────────────────────────────

func TestGenerateZprofile_Header(t *testing.T) {
	out := presets.GenerateZprofile(config.Config{
		Env: config.EnvConfig{Vars: map[string]string{}},
	})
	if !strings.HasPrefix(out, "# Generated by dots") {
		t.Fatalf("missing generated header, got: %q", out[:40])
	}
	if !strings.Contains(out, "Login shell only") {
		t.Error("missing login shell comment")
	}
}

func TestGenerateZprofile_EnvVarsSorted(t *testing.T) {
	cfg := config.Config{
		Env: config.EnvConfig{Vars: map[string]string{
			"ZEBRA": "z",
			"ALPHA": "a",
			"MANGO": "m",
		}},
	}
	out := presets.GenerateZprofile(cfg)
	posA := strings.Index(out, "ALPHA")
	posM := strings.Index(out, "MANGO")
	posZ := strings.Index(out, "ZEBRA")
	if posA > posM || posM > posZ {
		t.Error("env vars not in sorted order")
	}
	if !strings.Contains(out, `export ALPHA="a"`) {
		t.Error("missing ALPHA export")
	}
}

func TestGenerateZprofile_ShellPath(t *testing.T) {
	cfg := config.Config{
		Env:   config.EnvConfig{Vars: map[string]string{}},
		Shell: config.ShellConfig{Path: []string{"/custom/bin"}},
	}
	out := presets.GenerateZprofile(cfg)
	if !strings.Contains(out, "/custom/bin") {
		t.Error("missing shell path entry")
	}
	if !strings.Contains(out, `case ":$PATH:"`) {
		t.Error("missing idempotent PATH guard")
	}
}

func TestGenerateZprofile_ToolsBinDirPrepended(t *testing.T) {
	cfg := config.Config{
		Env:         config.EnvConfig{Vars: map[string]string{}},
		Shell:       config.ShellConfig{Path: []string{"/custom/bin"}},
		ToolsConfig: config.ToolsConfig{BinDir: "/tools/bin"},
		Tools:       []config.Tool{{Name: "rg"}},
	}
	out := presets.GenerateZprofile(cfg)
	posTools := strings.Index(out, "/tools/bin")
	posCustom := strings.Index(out, "/custom/bin")
	if posTools < 0 || posCustom < 0 {
		t.Fatal("missing path entries")
	}
	if posTools > posCustom {
		t.Error("bin_dir should appear before shell path entries")
	}
}

func TestGenerateZprofile_ToolPathDeduped(t *testing.T) {
	cfg := config.Config{
		Env:   config.EnvConfig{Vars: map[string]string{}},
		Shell: config.ShellConfig{Path: []string{"/shared/bin"}},
		Tools: []config.Tool{
			{Name: "rg", Shell: config.ToolShell{Path: []string{"/shared/bin", "/extra/bin"}}},
		},
		ToolsConfig: config.ToolsConfig{BinDir: "/tools/bin"},
	}
	out := presets.GenerateZprofile(cfg)
	// Each PATH guard line contains the path twice (pattern + export),
	// so count lines rather than raw occurrences.
	var sharedLines int
	for _, line := range strings.Split(out, "\n") {
		if strings.Contains(line, "/shared/bin") {
			sharedLines++
		}
	}
	if sharedLines != 1 {
		t.Errorf("/shared/bin appears in %d lines, want 1", sharedLines)
	}
}

func TestGenerateZprofile_EndsWithNewline(t *testing.T) {
	out := presets.GenerateZprofile(config.Config{
		Env: config.EnvConfig{Vars: map[string]string{}},
	})
	if !strings.HasSuffix(out, "\n") {
		t.Error("output should end with newline")
	}
}

func TestGenerateProfile_IdenticalToZprofile(t *testing.T) {
	cfg := config.Config{
		Env:   config.EnvConfig{Vars: map[string]string{"X": "1"}},
		Shell: config.ShellConfig{Path: []string{"/a"}},
	}
	if presets.GenerateProfile(cfg) != presets.GenerateZprofile(cfg) {
		t.Error("GenerateProfile should return the same output as GenerateZprofile")
	}
}
