package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

// newSampleCmd prints a fully-annotated dots.toml covering every section and
// key dots understands. It is the in-tool documentation of the schema: running
// `dots sample` (or `dots sample > dots.toml`) gives a new user a working,
// heavily-commented starting point instead of a blank file.
//
// sampleConfig is validated by TestSampleConfigIsValid, which loads it through
// the real parser — so if a key here ever drifts from the schema, the test
// fails and this file must be brought back in sync.
func newSampleCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "sample",
		Short: "Print a fully-commented example dots.toml",
		Long: "Print an annotated dots.toml that documents every section and option\n" +
			"dots understands, with liberal comments explaining what each key does\n" +
			"and its default. Redirect it to start a new config:\n\n" +
			"  dots sample > dots.toml",
		Aliases:     []string{"example"},
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"skipConfig": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			_, err := fmt.Fprint(cmd.OutOrStdout(), sampleConfig)
			return err
		},
	}
}

// sampleConfig is the annotated reference dots.toml. Every key that appears here
// is a real, validated key (see the schema in internal/config/validate.go).
// Comments carry the documentation; the actual values are illustrative defaults.
const sampleConfig = `# ─────────────────────────────────────────────────────────────────────────────
# dots.toml — dotfiles + tools + environment, declared in one file.
#
# This is a fully-commented reference generated by ` + "`dots sample`" + `. It shows
# every section and option dots understands. Delete what you don't need — every
# section is optional, and dots works with no config at all (it will simply
# mirror the files/ directory into your home directory).
#
# Conventions used below:
#   • Paths may use ~ (home) and $VAR (environment) — both are expanded.
#   • "managed = false" sections are inert; flip to true to opt in.
#   • Defaults are noted in comments; commented-out keys show the default value.
#   • Every operation is idempotent: running "dots apply" twice is a no-op.
# ─────────────────────────────────────────────────────────────────────────────


# ── [meta] ───────────────────────────────────────────────────────────────────
# Schema version and repo-wide deployment defaults.
[meta]
# Config schema version. Bump only when dots tells you to. Current max: 1.
version = 1

# How files are deployed by default when a [[file]] entry doesn't say otherwise:
#   "symlink" — link the deployed path back to the repo (edits flow both ways).
#   "copy"    — copy the file (deployed path is independent of the repo).
# Override per file with link = true/false on a [[file]] entry.
default_mode = "symlink"


# ── [env] — environment variables ────────────────────────────────────────────
# Plain KEY = "value" pairs exported by the managed shell. Keys MUST be
# UPPERCASE. Do NOT set PATH here — use [shell] path instead (see below).
[env]
EDITOR = "nvim"
PAGER = "less -R"
LANG = "en_US.UTF-8"
# Values are literal strings; they are not shell-expanded at apply time. Refer
# to other variables with normal shell syntax — the shell expands them at login.
LESS = "-R"

# Conditional variables: set a variable only when a condition holds. Repeat the
# [[env.when]] block for each conditional variable.
[[env.when]]
key = "HOMEBREW_PREFIX"    # variable to set
value = "/opt/homebrew"    # value to give it
only = ["darwin"]          # only on these platforms (see "only" note below)

[[env.when]]
key = "BAT_THEME"
value = "ansi"
if_tool = "bat"            # only if the tool named "bat" is installed


# ── [shell] — managed shell bootstrap ────────────────────────────────────────
# When managed, dots writes a small marker-delimited block into your rc file(s)
# that sources snippets from a dot-managed directory. Your rc file is never
# clobbered — only the block between the dots markers is owned by dots.
[shell]
managed = true

# Also manage login shells (~/.zprofile and ~/.profile) so PATH/env are set for
# non-interactive and login sessions, not just interactive ones. Default: false.
login = false

# Paths to the rc files dots edits. Defaults shown.
# zshrc  = "~/.zshrc"
# bashrc = "~/.bashrc"

# Directory holding the sourced snippet files. dots writes generated snippets
# here (e.g. from tools and presets); you can drop your own *.sh files in too.
# Default shown.
# dir = "~/.config/dots/shell.d"

# Directories prepended to PATH by the managed shell. This is the ONLY place to
# manage PATH (it's rejected in [env]). Order matters — earliest wins.
path = ["~/.local/bin", "~/.cargo/bin", "~/go/bin"]


# ── [git] — managed git config ───────────────────────────────────────────────
# When managed, dots generates a config file and adds an [include] to your
# ~/.gitconfig pointing at it. Your existing ~/.gitconfig is preserved.
[git]
managed = true
name = "Ada Lovelace"
email = "ada@example.com"
editor = "nvim"

# Default branch name for "git init". Default: "main".
default_branch = "main"

# Set pull.rebase = true. Default: false.
pull_rebase = true

# Commit signing. signingkey is your GPG/SSH signing key id; sign = true turns
# on commit.gpgsign. Both default to empty/false.
# signingkey = "0A46826A"
# sign = true


# ── [ssh] — managed SSH config ───────────────────────────────────────────────
# When managed, dots generates an SSH config fragment and adds an Include line
# to ~/.ssh/config. Each [[ssh.host]] becomes a "Host" stanza.
[ssh]
managed = true

# One block per host. "host" is the Host pattern; every other key is written
# verbatim as an SSH option (so any valid ssh_config keyword works — port,
# user, identityfile, forwardagent, proxyjump, …). Booleans render as yes/no
# and integers pass through, so port = 2222 and forwardagent = true both
# work naturally.
[[ssh.host]]
host = "github.com"
user = "git"
identityfile = "~/.ssh/id_ed25519"
forwardagent = false

[[ssh.host]]
host = "bastion"
hostname = "bastion.internal.example.com"
user = "ada"
port = 2222
only = ["linux"]           # restrict this host to certain platforms


# ── [tools] — where downloaded tool binaries land ────────────────────────────
[tools]
# Directory for binaries dots installs (github/script methods) and symlinks it
# creates. Put this on your PATH (see [shell] path). Default: "~/.local/bin".
bin_dir = "~/.local/bin"


# ── [[tool]] — declarative tool installation ─────────────────────────────────
# Each [[tool]] describes a program dots can install and check for. A tool may
# list multiple [[tool.install]] methods; dots uses the first one whose command
# is available on the current machine (e.g. brew on macOS, apt on Debian).
[[tool]]
name = "ripgrep"                 # required; also the CLI handle (dots tools ...)
desc = "fast recursive grep"     # shown in "dots tools list"
check = "rg --version"           # command that succeeds iff installed.
                                 # Default: "which <name>".
tags = ["cli", "search"]         # free-form; filter with "dots tools --tag"
only = ["linux", "darwin"]       # restrict to platforms (see "only" note)
# profile = "work"               # only install under this named profile

# Install methods, tried in order. Available methods:
#   pkg | apt | brew | cargo | go | pip | pipx | npm  — package managers
#   github  — download a release asset from GitHub
#   script  — run a raw shell command
#   manual  — print a note and skip (for things dots can't automate)
[[tool.install]]
method = "apt"
package = "ripgrep"              # package name for the manager (defaults to name)

[[tool.install]]
method = "brew"
package = "ripgrep"

[[tool.install]]
method = "cargo"
package = "ripgrep"

# A second tool, installed straight from GitHub releases, showing every
# github-method knob.
[[tool]]
name = "lazygit"
check = "lazygit --version"

[[tool.install]]
method = "github"
repo = "jesseduffield/lazygit"   # owner/repo
# Asset filename pattern. Tokens substituted at download time:
#   {version} tag without leading v   {arch}  x86_64|aarch64|armv7|i686
#   {os} linux|darwin|windows         {goarch} amd64|arm64|386
#   {name} the tool name
asset = "lazygit_{version}_Linux_{arch}.tar.gz"
binary = "lazygit"               # binary to extract from the archive
# binary_path = "bin/lazygit"    # exact path inside the archive (alt to binary)
# Remap the detected {arch} for tools with inconsistent naming. Only listed
# architectures are remapped; others pass through unchanged.
arch_map = { aarch64 = "arm64" }
# Pin a release, or omit / use "latest" to track the newest. dots records the
# installed version in ~/.config/dots/installed.toml (machine-local, not
# committed) and can assert/update it via "dots tools status|update".
version = "latest"
# install_dir extracts the WHOLE archive tree here and symlinks the binary from
# bin_dir into it — use for tools that need sibling runtime files (nvim, zig).
# install_dir = "~/.local/lazygit"

# Per-tool shell integration: extra env, PATH, and an init snippet emitted into
# the managed shell only when this tool is present. [tool.shell] attaches to the
# [[tool]] directly above it.
[tool.shell]
env = { LG_CONFIG_FILE = "~/.config/lazygit/config.yml" }
path = ["~/.local/share/lazygit/bin"]
init = "alias lg='lazygit'"

# Per-tool git integration: register this tool as git's pager and/or diff tool.
# [tool.git]
# pager = true
# diff = true

# A tool dots can't install automatically — just document it.
[[tool]]
name = "docker"
check = "docker --version"
[[tool.install]]
method = "manual"
note = "Install Docker Desktop from https://docker.com/products/docker-desktop"

# A tool installed by running a script (for vendor install scripts).
[[tool]]
name = "rustup"
check = "rustup --version"
[[tool.install]]
method = "script"
script = "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"


# ── [[file]] — explicit file deployment ──────────────────────────────────────
# dots auto-discovers everything under files/ (and files.d/<platform>/) and
# mirrors it into ~. Use [[file]] only when you need to override the source
# path, destination, deploy mode, or scope. Both src and dst are required.
[[file]]
src = "files/gitconfig"          # path relative to the repo root
dst = "~/.gitconfig"             # destination (~ and $VAR expanded)

[[file]]
src = "files/ssh_private_key.age"
dst = "~/.ssh/id_ed25519"
secret = true                    # decrypt with age on deploy (see [secrets])
mode = "0600"                    # octal permission bits for the deployed file
link = false                     # force copy for this file (overrides default_mode)

[[file]]
src = "files/work_netrc"
dst = "~/.netrc"
only = ["linux"]                 # deploy only on these platforms
profile = "work"                 # deploy only under this named profile


# ── [[repo]] — git repositories to clone ─────────────────────────────────────
# Each [[repo]] is cloned to dst and kept in sync. Managed with
# "dots repos clone|update|status".
[[repo]]
name = "tpm"                     # required handle
repo = "tmux-plugins/tpm"        # URL or owner/repo GitHub shorthand
dst = "~/.tmux/plugins/tpm"      # clone destination (~ expanded)
shallow = true                   # clone with --depth 1. Default: false.
# Ref to assert: a tag, branch, or SHA. Pinned tag/SHA is checked out exactly;
# a branch is reset to its remote tip. Omit or "latest" to track the default
# branch. A repo with uncommitted changes is skipped by update.
ref = "v3.1.0"
# Shell hooks run after the initial clone / after an update.
on_install = "~/.tmux/plugins/tpm/bin/install_plugins"
# on_update  = "echo updated"
only = ["linux", "darwin"]       # restrict to platforms
# profile = "personal"           # restrict to a named profile


# ── [secrets] — age encryption ───────────────────────────────────────────────
# dots encrypts/decrypts files with age (built in — no external binary needed).
# "dots encrypt <file>" produces <file>.age; files marked secret = true (or
# ending in .age) are decrypted on deploy.
[secrets]
# Public recipient(s) new files are encrypted to. An age recipient (age1...) or
# an ssh public key.
recipient = "age1ql3z7hjy54pw3hyww5ayyfg7zqgvc7w3j2elw8zmrj2kg5sfn9aqmcac8p"
# Private identity file used to decrypt. Machine-local; keep it out of the repo.
# Default: "~/.config/dots/key.txt".
identity = "~/.config/dots/key.txt"


# ── [presets] — opinionated bundles ──────────────────────────────────────────
# Turn on curated integrations dots generates for you. Both default to false.
[presets]
# fzf key-bindings + completion, emitted into the managed shell (requires
# [shell] managed = true).
fzf = true
# A sensible ~/.tmux.conf generated by dots.
tmux = false


# ── [profiles.*] — conditional overrides ─────────────────────────────────────
# Profiles layer partial config on top of the base. They are applied in order:
#   1. the current platform  (linux | darwin | windows | termux)
#   2. the current hostname
#   3. a manual profile passed with --profile <name>
# Later layers win. A profile subtree may override any section or append to any
# array-of-tables ([[tool]], [[file]], [[repo]], [[ssh.host]], [[env.when]]).
#
# Example: a "work" profile activated with: dots --profile work apply
[profiles.work]
[profiles.work.git]
email = "ada@work-corp.com"
signingkey = "ABCD1234"
sign = true

# Append a work-only tool.
[[profiles.work.tool]]
name = "awscli"
check = "aws --version"
[[profiles.work.tool.install]]
method = "brew"
package = "awscli"

# Example: platform-named profile applied automatically on macOS.
[profiles.darwin]
[profiles.darwin.shell]
path = ["/opt/homebrew/bin", "~/.local/bin"]
`
