package ssh

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pkuehne/dots/internal/config"
)

func TestSnakeToSSHKeyword_KnownKeys(t *testing.T) {
	cases := []struct {
		in, want string
	}{
		{"identity_file", "IdentityFile"},
		{"forward_agent", "ForwardAgent"},
		{"strict_host_key_checking", "StrictHostKeyChecking"},
		{"proxy_jump", "ProxyJump"},
		{"user", "User"},
		{"port", "Port"},
	}
	for _, tc := range cases {
		got := SnakeToSSHKeyword(tc.in)
		if got != tc.want {
			t.Errorf("SnakeToSSHKeyword(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestSnakeToSSHKeyword_FallbackToPascalCase(t *testing.T) {
	got := SnakeToSSHKeyword("some_unknown_key")
	if got != "SomeUnknownKey" {
		t.Errorf("expected PascalCase fallback, got %q", got)
	}
}

func TestGenerateConfig_Header(t *testing.T) {
	cfg := config.Config{}
	result := GenerateConfig(cfg, []string{"linux"})
	if !strings.Contains(result, "Generated by dots") {
		t.Error("expected generated header")
	}
}

func TestGenerateConfig_Basic(t *testing.T) {
	cfg := config.Config{}
	cfg.SSH.Hosts = []config.SSHHost{
		{
			Host:    "*.internal",
			Options: map[string]string{"user": "peter", "identity_file": "~/.ssh/id_ed25519"},
		},
	}
	result := GenerateConfig(cfg, []string{"linux"})
	if !strings.Contains(result, "Host *.internal") {
		t.Error("expected Host entry")
	}
	if !strings.Contains(result, "User peter") {
		t.Error("expected User option")
	}
	if !strings.Contains(result, "IdentityFile ~/.ssh/id_ed25519") {
		t.Error("expected IdentityFile option")
	}
}

func TestGenerateConfig_PlatformFilter(t *testing.T) {
	cfg := config.Config{}
	cfg.SSH.Hosts = []config.SSHHost{
		{
			Host:    "*.internal",
			Only:    []string{"linux", "darwin"},
			Options: map[string]string{"user": "peter"},
		},
	}

	result := GenerateConfig(cfg, []string{"termux"})
	if strings.Contains(result, "Host *.internal") {
		t.Error("host should be filtered for termux")
	}

	result = GenerateConfig(cfg, []string{"linux"})
	if !strings.Contains(result, "Host *.internal") {
		t.Error("host should appear for linux")
	}
}

func TestGenerateConfig_MultipleHosts(t *testing.T) {
	cfg := config.Config{}
	cfg.SSH.Hosts = []config.SSHHost{
		{Host: "host1", Options: map[string]string{"user": "alice"}},
		{Host: "host2", Options: map[string]string{"user": "bob", "port": "2222"}},
	}
	result := GenerateConfig(cfg, []string{"linux"})
	if !strings.Contains(result, "Host host1") {
		t.Error("expected host1")
	}
	if !strings.Contains(result, "Host host2") {
		t.Error("expected host2")
	}
	if !strings.Contains(result, "User alice") {
		t.Error("expected alice")
	}
	if !strings.Contains(result, "User bob") {
		t.Error("expected bob")
	}
	if !strings.Contains(result, "Port 2222") {
		t.Error("expected port")
	}
}

func TestGenerateConfig_Deterministic(t *testing.T) {
	cfg := config.Config{}
	cfg.SSH.Hosts = []config.SSHHost{
		{
			Host: "*.internal",
			Options: map[string]string{
				"user":          "peter",
				"port":          "2222",
				"identity_file": "~/.ssh/id_ed25519",
				"forward_agent": "yes",
			},
		},
	}

	first := GenerateConfig(cfg, []string{"linux"})
	for i := 0; i < 20; i++ {
		if got := GenerateConfig(cfg, []string{"linux"}); got != first {
			t.Fatalf("GenerateConfig output not deterministic:\n--- first ---\n%s\n--- got ---\n%s", first, got)
		}
	}
}

func TestWriteManaged_DryRun(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	if err := WriteManaged(cfg, []string{"linux"}, true); err != nil {
		t.Fatalf("WriteManaged dry-run: %v", err)
	}
	// No files should be created.
	if _, err := os.Stat(filepath.Join(home, ".config", "dots", "ssh", "config")); !os.IsNotExist(err) {
		t.Error("dry-run must not create ssh config file")
	}
}

func TestWriteManaged_CreatesFile(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	cfg.SSH.Hosts = []config.SSHHost{
		{Host: "myhost", Options: map[string]string{"user": "alice"}},
	}

	if err := WriteManaged(cfg, []string{"linux"}, false); err != nil {
		t.Fatalf("WriteManaged: %v", err)
	}

	outPath := filepath.Join(home, ".config", "dots", "ssh", "config")
	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("reading ssh config: %v", err)
	}
	if !strings.Contains(string(data), "Host myhost") {
		t.Error("ssh config missing host entry")
	}
}

func TestWriteManaged_InsertsIncludeLine(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	if err := WriteManaged(cfg, []string{"linux"}, false); err != nil {
		t.Fatalf("WriteManaged: %v", err)
	}

	sshConfig := filepath.Join(home, ".ssh", "config")
	data, err := os.ReadFile(sshConfig)
	if err != nil {
		t.Fatalf("reading ~/.ssh/config: %v", err)
	}
	if !strings.Contains(string(data), sshIncludeLine) {
		t.Error("~/.ssh/config missing Include line")
	}
}

func TestWriteManaged_Idempotent(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	if err := WriteManaged(cfg, []string{"linux"}, false); err != nil {
		t.Fatal(err)
	}
	if err := WriteManaged(cfg, []string{"linux"}, false); err != nil {
		t.Fatal(err)
	}

	sshConfig := filepath.Join(home, ".ssh", "config")
	data, _ := os.ReadFile(sshConfig)
	count := strings.Count(string(data), sshIncludeLine)
	if count != 1 {
		t.Errorf("expected Include line once, got %d", count)
	}
}

func TestWriteManaged_PrependToExisting(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	sshDir := filepath.Join(home, ".ssh")
	if err := os.MkdirAll(sshDir, 0o700); err != nil {
		t.Fatal(err)
	}
	sshConfig := filepath.Join(sshDir, "config")
	existing := "Host existing\n    User me\n"
	if err := os.WriteFile(sshConfig, []byte(existing), 0o600); err != nil {
		t.Fatal(err)
	}

	cfg := config.Config{}
	if err := WriteManaged(cfg, []string{"linux"}, false); err != nil {
		t.Fatal(err)
	}

	data, _ := os.ReadFile(sshConfig)
	text := string(data)
	if !strings.HasPrefix(text, sshIncludeLine) {
		t.Error("Include line should be prepended")
	}
	if !strings.Contains(text, "Host existing") {
		t.Error("existing content should be preserved")
	}
}

func TestUninit_RemovesIncludeLine(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	if err := WriteManaged(cfg, []string{"linux"}, false); err != nil {
		t.Fatal(err)
	}
	if err := Uninit(cfg, false); err != nil {
		t.Fatalf("Uninit: %v", err)
	}

	sshConfig := filepath.Join(home, ".ssh", "config")
	data, _ := os.ReadFile(sshConfig)
	if strings.Contains(string(data), sshIncludeLine) {
		t.Error("expected Include line to be removed")
	}
}

func TestUninit_DryRun(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	if err := WriteManaged(cfg, []string{"linux"}, false); err != nil {
		t.Fatal(err)
	}
	if err := Uninit(cfg, true); err != nil {
		t.Fatalf("Uninit dry-run: %v", err)
	}

	sshConfig := filepath.Join(home, ".ssh", "config")
	data, _ := os.ReadFile(sshConfig)
	if !strings.Contains(string(data), sshIncludeLine) {
		t.Error("dry-run uninit must not modify the file")
	}
}

func TestUninit_NoopWhenAbsent(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)

	cfg := config.Config{}
	if err := Uninit(cfg, false); err != nil {
		t.Fatalf("Uninit on non-existent file: %v", err)
	}
}
