// Package shell manages the shell.d snippet directory and the marker-delimited
// source line inserted into ~/.zshrc / ~/.bashrc.
package shell

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/pkuehne/dots/internal/config"
	"github.com/pkuehne/dots/internal/fileutil"
	"github.com/pkuehne/dots/internal/platform"
)

// Marker constants reused by the git, ssh, and presets subsystems.
const (
	GeneratedHeader = "# Generated by dots — do not edit directly."
	MarkerStart     = "# >>> dots managed — do not edit between these markers >>>"
	MarkerEnd       = "# <<< dots managed <<<"
)

var zshBootstrapper = MarkerStart + "\n" +
	`_dots_d="${XDG_CONFIG_HOME:-$HOME/.config}/dots/shell.d"` + "\n" +
	`if [[ -d "$_dots_d" ]]; then` + "\n" +
	`  for _dots_f in "$_dots_d"/[0-9]*.sh "$_dots_d"/[0-9]*.zsh; do` + "\n" +
	`    [[ -f "$_dots_f" ]] && source "$_dots_f"` + "\n" +
	`  done` + "\n" +
	`  unset _dots_f _dots_d` + "\n" +
	`fi` + "\n" +
	MarkerEnd

var bashBootstrapper = MarkerStart + "\n" +
	`_dots_d="${XDG_CONFIG_HOME:-$HOME/.config}/dots/shell.d"` + "\n" +
	`if [ -d "$_dots_d" ]; then` + "\n" +
	`  for _dots_f in "$_dots_d"/[0-9]*.sh "$_dots_d"/[0-9]*.bash; do` + "\n" +
	`    [ -f "$_dots_f" ] && . "$_dots_f"` + "\n" +
	`  done` + "\n" +
	`  unset _dots_f _dots_d` + "\n" +
	`fi` + "\n" +
	MarkerEnd

// GenerateEnvSnippet returns the content of 010-env.sh derived from cfg.Env.
func GenerateEnvSnippet(cfg config.Config) string {
	return generateEnvSnippet(cfg, platform.Platforms())
}

func generateEnvSnippet(cfg config.Config, plats []string) string {
	lines := []string{
		GeneratedHeader,
		"# Source: [env] + [[env.when]]",
		"# Regenerate: dots apply",
		"",
	}

	keys := make([]string, 0, len(cfg.Env.Vars))
	for k := range cfg.Env.Vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		lines = append(lines, fmt.Sprintf(`export %s="%s"`, k, cfg.Env.Vars[k]))
	}

	for _, ew := range cfg.Env.When {
		if len(ew.Only) > 0 && !intersects(ew.Only, plats) {
			continue
		}
		if ew.IfTool != "" {
			lines = append(lines, "")
			lines = append(lines, fmt.Sprintf(`command -v %s >/dev/null 2>&1 && export %s="%s"`, ew.IfTool, ew.Key, ew.Value))
		} else {
			lines = append(lines, fmt.Sprintf(`export %s="%s"`, ew.Key, ew.Value))
		}
	}

	return strings.Join(lines, "\n") + "\n"
}

// GeneratePathSnippet returns the content of 020-path.sh.
// Paths are collected from cfg.Shell.Path, per-tool shell.path entries, and
// cfg.ToolsConfig.BinDir (prepended when tools are configured). Duplicates are
// removed while preserving order.
func GeneratePathSnippet(cfg config.Config) string {
	lines := []string{
		GeneratedHeader,
		"# Source: [shell] path + [[tool]] shell.path",
		"# Regenerate: dots apply",
		"",
	}

	paths := make([]string, len(cfg.Shell.Path))
	copy(paths, cfg.Shell.Path)

	for _, tool := range cfg.Tools {
		for _, p := range tool.Shell.Path {
			if !sliceContains(paths, p) {
				paths = append(paths, p)
			}
		}
	}

	if len(cfg.Tools) > 0 {
		binDir := cfg.ToolsConfig.BinDir
		if !sliceContains(paths, binDir) {
			paths = append([]string{binDir}, paths...)
		}
	}

	seen := make(map[string]bool, len(paths))
	deduped := make([]string, 0, len(paths))
	for _, p := range paths {
		if !seen[p] {
			seen[p] = true
			deduped = append(deduped, p)
		}
	}

	for _, p := range deduped {
		expanded := fileutil.Expand(p)
		lines = append(lines, fmt.Sprintf(
			`case ":$PATH:" in *":%s:"*) ;; *) export PATH="%s:$PATH" ;; esac`,
			expanded, expanded,
		))
	}

	return strings.Join(lines, "\n") + "\n"
}

// GenerateToolSnippet returns the content of 050-{name}.sh for one tool.
// shellName is substituted for {shell} in tool.Shell.Init (typically "zsh" or "bash").
func GenerateToolSnippet(tool config.Tool, shellName string) string {
	guard := tool.Name
	if strings.HasPrefix(tool.Check, "which ") {
		parts := strings.Fields(tool.Check)
		if len(parts) > 1 {
			guard = parts[1]
		}
	}

	lines := []string{
		GeneratedHeader,
		fmt.Sprintf("# Source: [[tool]] %s shell.*", tool.Name),
		"# Regenerate: dots apply",
		"",
		fmt.Sprintf("command -v %s >/dev/null 2>&1 || return", guard),
		"",
	}

	keys := make([]string, 0, len(tool.Shell.Env))
	for k := range tool.Shell.Env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		lines = append(lines, fmt.Sprintf(`export %s="%s"`, k, tool.Shell.Env[k]))
	}

	if tool.Shell.Init != "" {
		initCmd := strings.ReplaceAll(tool.Shell.Init, "{shell}", shellName)
		lines = append(lines, "")
		lines = append(lines, initCmd)
	}

	return strings.Join(lines, "\n") + "\n"
}

// GenerateCustomSnippet reads files/.zshrc from repoRoot and wraps it in a
// generated-file header. Returns the content, true if found, and any error.
func GenerateCustomSnippet(repoRoot string) (string, bool, error) {
	zshrc := filepath.Join(repoRoot, "files", ".zshrc")
	data, err := os.ReadFile(zshrc)
	if err != nil {
		if os.IsNotExist(err) {
			return "", false, nil
		}
		return "", false, err
	}

	lines := []string{
		GeneratedHeader,
		"# Source: files/.zshrc (migration aid)",
		"# Regenerate: dots apply",
		"",
		strings.TrimRight(string(data), "\n"),
	}
	return strings.Join(lines, "\n") + "\n", true, nil
}

// userSnippetFiles lists the regular files in <repoRoot>/shell/ that dots
// deploys into shell.d. Both deployUserSnippets and Clean derive their view of
// user snippets from this list so the two cannot drift apart.
func userSnippetFiles(repoRoot string) ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(repoRoot, "shell"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() || fileutil.ShouldSkip(e.Name()) {
			continue
		}
		names = append(names, e.Name())
	}
	return names, nil
}

// userSnippetPrefixRe matches a leading numeric prefix in a snippet name.
var userSnippetPrefixRe = regexp.MustCompile(`^(\d+)`)

// deployUserSnippets copies user snippet files from <repoRoot>/shell/ into
// dir, warning when a numeric prefix falls outside the ranges reserved for
// user snippets (030-049, 080-089, 090+; generated snippets own the rest).
// .j2 templates are not supported in the Go version and are skipped visibly.
func deployUserSnippets(cfg config.Config, dir string, dryRun bool) error {
	names, err := userSnippetFiles(cfg.RepoRoot)
	if err != nil {
		return err
	}
	for _, name := range names {
		if m := userSnippetPrefixRe.FindStringSubmatch(name); m != nil {
			prefix, _ := strconv.Atoi(m[1])
			inRange := (prefix >= 30 && prefix <= 49) ||
				(prefix >= 80 && prefix <= 89) ||
				(prefix >= 90 && prefix <= 99)
			if !inRange {
				fmt.Printf("  ⚠ Warning: %s has prefix %d outside expected ranges "+
					"(030-049, 080-089, 090+)\n", name, prefix)
			}
		}
		if strings.HasSuffix(name, ".j2") {
			fmt.Printf("  skipped %s (template — not supported)\n", name)
			continue
		}
		if dryRun {
			continue
		}
		src := filepath.Join(cfg.RepoRoot, "shell", name)
		if err := fileutil.CopyFile(src, filepath.Join(dir, name)); err != nil {
			return err
		}
	}
	return nil
}

// toolSnippetFiles returns the snippet filename → shell-name pairs to generate
// for one tool, or nil when the tool has no shell integration. A tool whose
// init contains the {shell} placeholder gets per-shell variants (.zsh/.bash,
// each only sourced by the matching bootstrapper); otherwise a single
// shell-neutral .sh. WriteSnippets and Clean both derive snippet names from
// this so the two cannot drift apart.
func toolSnippetFiles(tool config.Tool) map[string]string {
	if len(tool.Shell.Env) == 0 && tool.Shell.Init == "" {
		return nil
	}
	if strings.Contains(tool.Shell.Init, "{shell}") {
		return map[string]string{
			fmt.Sprintf("050-%s.zsh", tool.Name):  "zsh",
			fmt.Sprintf("050-%s.bash", tool.Name): "bash",
		}
	}
	return map[string]string{fmt.Sprintf("050-%s.sh", tool.Name): "bash"}
}

// WriteSnippets writes all generated snippets to cfg.Shell.Dir and deploys
// user snippets from <repoRoot>/shell/. User snippets are deployed first, so
// a generated snippet wins if a user file shares its name.
// With dryRun=true no files are written.
func WriteSnippets(cfg config.Config, dryRun bool) error {
	dir := fileutil.Expand(cfg.Shell.Dir)

	if !dryRun {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}

	if err := deployUserSnippets(cfg, dir, dryRun); err != nil {
		return err
	}

	snippets := map[string]string{
		"010-env.sh":  GenerateEnvSnippet(cfg),
		"020-path.sh": GeneratePathSnippet(cfg),
	}
	for _, tool := range cfg.Tools {
		for name, shellName := range toolSnippetFiles(tool) {
			snippets[name] = GenerateToolSnippet(tool, shellName)
		}
	}
	if custom, ok, err := GenerateCustomSnippet(cfg.RepoRoot); err != nil {
		return err
	} else if ok {
		snippets["099-custom.sh"] = custom
	}

	if dryRun {
		return nil
	}

	for name, content := range snippets {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// InsertSourceLine inserts the marker-delimited bootstrapper block into the
// zshrc and bashrc files listed in cfg.Shell.
func InsertSourceLine(cfg config.Config, dryRun bool) error {
	if _, err := InsertBlock(fileutil.Expand(cfg.Shell.Zshrc), zshBootstrapper, dryRun); err != nil {
		return err
	}
	if _, err := InsertBlock(fileutil.Expand(cfg.Shell.Bashrc), bashBootstrapper, dryRun); err != nil {
		return err
	}
	return nil
}

// Assembled returns the concatenated content of all snippet files in shell.d,
// sorted by filename.
func Assembled(cfg config.Config) (string, error) {
	dir := fileutil.Expand(cfg.Shell.Dir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}

	var sb strings.Builder
	for _, e := range entries {
		if e.IsDir() || !isSnippetFile(e.Name()) {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return "", err
		}
		sb.Write(data)
	}
	return sb.String(), nil
}

// Clean removes snippet files from shell.d that are not expected given the
// current config. With dryRun=true no files are removed.
func Clean(cfg config.Config, dryRun bool) error {
	dir := fileutil.Expand(cfg.Shell.Dir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	expected := map[string]bool{
		"010-env.sh":  true,
		"020-path.sh": true,
	}
	// Keep in sync with applyPresets in cmd/dots/commands.go, which writes
	// 030-fzf.sh into shell.d when the fzf preset is enabled. Without this
	// entry, Clean would delete the preset that apply just wrote.
	if cfg.Presets.Fzf {
		expected["030-fzf.sh"] = true
	}
	for _, tool := range cfg.Tools {
		for name := range toolSnippetFiles(tool) {
			expected[name] = true
		}
	}
	if _, ok, _ := GenerateCustomSnippet(cfg.RepoRoot); ok {
		expected["099-custom.sh"] = true
	}
	// User snippets deployed from <repoRoot>/shell/ by deployUserSnippets must
	// never be cleaned; both sides derive the list from userSnippetFiles.
	if names, err := userSnippetFiles(cfg.RepoRoot); err == nil {
		for _, n := range names {
			expected[n] = true
		}
	}

	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !isSnippetFile(name) || expected[name] {
			continue
		}
		if !dryRun {
			if err := os.Remove(filepath.Join(dir, name)); err != nil {
				return err
			}
		}
	}
	return nil
}

// InsertBlock idempotently inserts content into path using marker-delimited
// replacement. If the file already contains MarkerStart, the block is updated
// in place; otherwise content is appended. Returns true if modified.
func InsertBlock(path, content string, dryRun bool) (bool, error) {
	_, statErr := os.Lstat(path)
	if os.IsNotExist(statErr) {
		if dryRun {
			return true, nil
		}
		// Remove dangling symlink if present.
		if _, lerr := os.Readlink(path); lerr == nil {
			_ = os.Remove(path)
		}
		if err := fileutil.EnsureParent(path); err != nil {
			return false, err
		}
		return true, os.WriteFile(path, []byte(content+"\n"), 0o644)
	}
	if statErr != nil {
		return false, statErr
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	text := string(data)

	if strings.Contains(text, MarkerStart) {
		re := regexp.MustCompile(`(?s)` + regexp.QuoteMeta(MarkerStart) + `.*?` + regexp.QuoteMeta(MarkerEnd))
		newText := re.ReplaceAllString(text, content)
		if newText == text {
			return false, nil
		}
		if dryRun {
			return true, nil
		}
		return true, os.WriteFile(path, []byte(newText), 0o644)
	}

	if !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	text += "\n" + content + "\n"
	if dryRun {
		return true, nil
	}
	return true, os.WriteFile(path, []byte(text), 0o644)
}

// RemoveBlock removes the marker-delimited block from path.
// Returns true if the file was modified.
func RemoveBlock(path string, dryRun bool) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	text := string(data)

	if !strings.Contains(text, MarkerStart) {
		return false, nil
	}

	re := regexp.MustCompile(`(?s)\n?` + regexp.QuoteMeta(MarkerStart) + `.*?` + regexp.QuoteMeta(MarkerEnd) + `\n?`)
	newText := re.ReplaceAllString(text, "\n")
	if dryRun {
		return true, nil
	}
	return true, os.WriteFile(path, []byte(newText), 0o644)
}

func isSnippetFile(name string) bool {
	if len(name) == 0 || name[0] < '0' || name[0] > '9' {
		return false
	}
	return strings.HasSuffix(name, ".sh") ||
		strings.HasSuffix(name, ".zsh") ||
		strings.HasSuffix(name, ".bash")
}

func sliceContains(slice []string, s string) bool {
	for _, v := range slice {
		if v == s {
			return true
		}
	}
	return false
}

// intersects reports whether any element of a is present in b.
func intersects(a, b []string) bool {
	for _, x := range a {
		if sliceContains(b, x) {
			return true
		}
	}
	return false
}
