// Package shell manages the shell.d snippet directory and the marker-delimited
// source line inserted into ~/.zshrc / ~/.bashrc.
package shell

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/pkuehne/dots/internal/config"
	"github.com/pkuehne/dots/internal/fileutil"
	"github.com/pkuehne/dots/internal/platform"
	"github.com/pkuehne/dots/internal/ui"
)

// Marker constants reused by the git, ssh, and presets subsystems.
const (
	GeneratedHeader = "# Generated by dots — do not edit directly."
	MarkerStart     = "# >>> dots managed — do not edit between these markers >>>"
	MarkerEnd       = "# <<< dots managed <<<"
)

var zshBootstrapper = MarkerStart + "\n" +
	`_dots_d="${XDG_CONFIG_HOME:-$HOME/.config}/dots/shell.d"` + "\n" +
	`if [[ -d "$_dots_d" ]]; then` + "\n" +
	`  for _dots_f in "$_dots_d"/[0-9]*.sh "$_dots_d"/[0-9]*.zsh; do` + "\n" +
	`    [[ -f "$_dots_f" ]] && source "$_dots_f"` + "\n" +
	`  done` + "\n" +
	`  unset _dots_f _dots_d` + "\n" +
	`fi` + "\n" +
	MarkerEnd

var bashBootstrapper = MarkerStart + "\n" +
	`_dots_d="${XDG_CONFIG_HOME:-$HOME/.config}/dots/shell.d"` + "\n" +
	`if [ -d "$_dots_d" ]; then` + "\n" +
	`  for _dots_f in "$_dots_d"/[0-9]*.sh "$_dots_d"/[0-9]*.bash; do` + "\n" +
	`    [ -f "$_dots_f" ] && . "$_dots_f"` + "\n" +
	`  done` + "\n" +
	`  unset _dots_f _dots_d` + "\n" +
	`fi` + "\n" +
	MarkerEnd

// GenerateEnvSnippet returns the content of 010-env.sh derived from cfg.Env.
func GenerateEnvSnippet(cfg config.Config) string {
	return generateEnvSnippet(cfg, platform.Platforms())
}

func generateEnvSnippet(cfg config.Config, plats []string) string {
	lines := []string{
		GeneratedHeader,
		"# Source: [env] + [[env.when]]",
		"# Regenerate: dots apply",
		"",
	}

	keys := make([]string, 0, len(cfg.Env.Vars))
	for k := range cfg.Env.Vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		lines = append(lines, fmt.Sprintf(`export %s="%s"`, k, cfg.Env.Vars[k]))
	}

	for _, ew := range cfg.Env.When {
		if len(ew.Only) > 0 && !intersects(ew.Only, plats) {
			continue
		}
		if ew.IfTool != "" {
			lines = append(lines, "")
			lines = append(lines, fmt.Sprintf(`command -v %s >/dev/null 2>&1 && export %s="%s"`, ew.IfTool, ew.Key, ew.Value))
		} else {
			lines = append(lines, fmt.Sprintf(`export %s="%s"`, ew.Key, ew.Value))
		}
	}

	return strings.Join(lines, "\n") + "\n"
}

// GeneratePathSnippet returns the content of 020-path.sh.
// Paths are collected from cfg.Shell.Path, per-tool shell.path entries, and
// cfg.ToolsConfig.BinDir (prepended when tools are configured). Duplicates are
// removed while preserving order.
func GeneratePathSnippet(cfg config.Config) string {
	lines := []string{
		GeneratedHeader,
		"# Source: [shell] path + [[tool]] shell.path",
		"# Regenerate: dots apply",
		"",
	}

	paths := make([]string, len(cfg.Shell.Path))
	copy(paths, cfg.Shell.Path)

	for _, tool := range cfg.Tools {
		for _, p := range tool.Shell.Path {
			if !sliceContains(paths, p) {
				paths = append(paths, p)
			}
		}
	}

	if len(cfg.Tools) > 0 {
		binDir := cfg.ToolsConfig.BinDir
		if !sliceContains(paths, binDir) {
			paths = append([]string{binDir}, paths...)
		}
	}

	seen := make(map[string]bool, len(paths))
	deduped := make([]string, 0, len(paths))
	for _, p := range paths {
		if !seen[p] {
			seen[p] = true
			deduped = append(deduped, p)
		}
	}

	for _, p := range deduped {
		expanded := fileutil.Expand(p)
		lines = append(lines, fmt.Sprintf(
			`case ":$PATH:" in *":%s:"*) ;; *) export PATH="%s:$PATH" ;; esac`,
			expanded, expanded,
		))
	}

	return strings.Join(lines, "\n") + "\n"
}

// GenerateToolSnippet returns the content of 050-{name}.sh for one tool.
// shellName is substituted for {shell} in tool.Shell.Init (typically "zsh" or "bash").
func GenerateToolSnippet(tool config.Tool, shellName string) string {
	guard := tool.Name
	if strings.HasPrefix(tool.Check, "which ") {
		parts := strings.Fields(tool.Check)
		if len(parts) > 1 {
			guard = parts[1]
		}
	}

	lines := []string{
		GeneratedHeader,
		fmt.Sprintf("# Source: [[tool]] %s shell.*", tool.Name),
		"# Regenerate: dots apply",
		"",
		fmt.Sprintf("command -v %s >/dev/null 2>&1 || return", guard),
		"",
	}

	keys := make([]string, 0, len(tool.Shell.Env))
	for k := range tool.Shell.Env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		lines = append(lines, fmt.Sprintf(`export %s="%s"`, k, tool.Shell.Env[k]))
	}

	if tool.Shell.Init != "" {
		initCmd := strings.ReplaceAll(tool.Shell.Init, "{shell}", shellName)
		lines = append(lines, "")
		lines = append(lines, initCmd)
	}

	return strings.Join(lines, "\n") + "\n"
}

// GenerateCustomSnippet reads files/.zshrc from repoRoot and wraps it in a
// generated-file header. Returns the content, true if found, and any error.
func GenerateCustomSnippet(repoRoot string) (string, bool, error) {
	zshrc := filepath.Join(repoRoot, "files", ".zshrc")
	data, err := os.ReadFile(zshrc)
	if err != nil {
		if os.IsNotExist(err) {
			return "", false, nil
		}
		return "", false, err
	}

	// Strip any dots-managed marker block. files/.zshrc may be deployed as a
	// symlink to ~/.zshrc, and InsertSourceLine writes the bootstrapper through
	// that symlink back into the repo file. Wrapping the block (which sources
	// shell.d) into 099-custom.sh — itself sourced by that loop — would recurse
	// infinitely. The bootstrapper belongs in ~/.zshrc, never in a snippet.
	body := stripMarkerBlock(string(data))

	lines := []string{
		GeneratedHeader,
		"# Source: files/.zshrc (migration aid)",
		"# Regenerate: dots apply",
		"",
		strings.TrimRight(body, "\n"),
	}
	return strings.Join(lines, "\n") + "\n", true, nil
}

// stripMarkerBlock removes every dots-managed marker block from text.
func stripMarkerBlock(text string) string {
	if !strings.Contains(text, MarkerStart) {
		return text
	}
	re := regexp.MustCompile(`(?s)\n?` + regexp.QuoteMeta(MarkerStart) + `.*?` + regexp.QuoteMeta(MarkerEnd) + `\n?`)
	return re.ReplaceAllString(text, "\n")
}

// userSnippetFiles lists the regular files in <repoRoot>/shell/ that dots
// deploys into shell.d. Both deployUserSnippets and Clean derive their view of
// user snippets from this list so the two cannot drift apart.
func userSnippetFiles(repoRoot string) ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(repoRoot, "shell"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var names []string
	for _, e := range entries {
		if e.IsDir() || fileutil.ShouldSkip(e.Name()) {
			continue
		}
		names = append(names, e.Name())
	}
	return names, nil
}

// userSnippetPrefixRe matches a leading numeric prefix in a snippet name.
var userSnippetPrefixRe = regexp.MustCompile(`^(\d+)`)

// deployUserSnippets copies user snippet files from <repoRoot>/shell/ into
// dir, warning when a numeric prefix falls outside the ranges reserved for
// user snippets (030-049, 080-089, 090+; generated snippets own the rest).
// snippetCounts tallies how many snippets/rc files were written versus left
// unchanged, so the Shell section can print a summary line like the file, repo
// and tool sections instead of going silent on an idempotent re-run.
type snippetCounts struct{ wrote, unchanged, removed int }

func (c *snippetCounts) add(changed bool) {
	if changed {
		c.wrote++
	} else {
		c.unchanged++
	}
}

func deployUserSnippets(cfg config.Config, dir string, dryRun, summary bool, sec *ui.Section, c *snippetCounts) error {
	names, err := userSnippetFiles(cfg.RepoRoot)
	if err != nil {
		return err
	}
	for _, name := range names {
		if m := userSnippetPrefixRe.FindStringSubmatch(name); m != nil {
			prefix, _ := strconv.Atoi(m[1])
			inRange := (prefix >= 30 && prefix <= 49) ||
				(prefix >= 80 && prefix <= 89) ||
				prefix >= 90
			if !inRange {
				ui.Warn("Warning: %s has prefix %d outside expected ranges "+
					"(030-049, 080-089, 090+)", name, prefix)
			}
		}
		src := filepath.Join(cfg.RepoRoot, "shell", name)
		content, err := os.ReadFile(src)
		if err != nil {
			return err
		}
		if err := writeSnippet(filepath.Join(dir, name), content, dryRun, summary, sec, c); err != nil {
			return err
		}
	}
	return nil
}

// writeSnippet writes one shell.d snippet idempotently and reports it as a row
// under sec: "wrote" when the content changed, otherwise "unchanged" (suppressed
// in summary mode). Listing untouched snippets keeps the Shell section
// consistent with the file/repo/tool sections, which always show their full set.
func writeSnippet(dst string, content []byte, dryRun, summary bool, sec *ui.Section, c *snippetCounts) error {
	changed, err := fileutil.WriteIfChanged(dst, content, 0o644, dryRun)
	if err != nil {
		return err
	}
	c.add(changed)
	if !summary {
		if changed {
			sec.Status("wrote", dst, dryRun)
		} else {
			sec.Status("unchanged", dst, dryRun)
		}
	}
	return nil
}

// toolSnippetFiles returns the snippet filename → shell-name pairs to generate
// for one tool, or nil when the tool has no shell integration or its Only does
// not intersect the active platform tags. A tool whose init contains the
// {shell} placeholder gets per-shell variants (.zsh/.bash, each only sourced
// by the matching bootstrapper); otherwise a single shell-neutral .sh.
// WriteSnippets and Clean both derive snippet names from this so the two
// cannot drift apart.
func toolSnippetFiles(tool config.Tool, platforms []string) map[string]string {
	if len(tool.Shell.Env) == 0 && tool.Shell.Init == "" {
		return nil
	}
	if len(tool.Only) > 0 && !intersects(tool.Only, platforms) {
		return nil
	}
	if strings.Contains(tool.Shell.Init, "{shell}") {
		return map[string]string{
			fmt.Sprintf("050-%s.zsh", tool.Name):  "zsh",
			fmt.Sprintf("050-%s.bash", tool.Name): "bash",
		}
	}
	return map[string]string{fmt.Sprintf("050-%s.sh", tool.Name): "bash"}
}

// Apply renders the whole Shell section: it writes the snippets and inserts the
// rc bootstrapper, then prints a header, one row per managed item and a summary
// tally — matching the file, repo and tool sections so the section stays visible
// on an idempotent re-run. In summary mode the unchanged rows are suppressed but
// the header and tally still print. sec may be nil. With dryRun=true no files
// are written.
func Apply(cfg config.Config, dryRun, summary bool, sec *ui.Section) error {
	sec.Header()
	var c snippetCounts
	if err := writeSnippets(cfg, dryRun, summary, sec, &c); err != nil {
		return err
	}
	if err := cleanStale(cfg, dryRun, sec, &c); err != nil {
		return err
	}
	if err := insertSourceLine(cfg, dryRun, summary, sec, &c); err != nil {
		return err
	}
	summaryLine := ui.ChangeTally(c.wrote, c.unchanged, dryRun)
	if c.removed > 0 {
		verb := "removed"
		if dryRun {
			verb = "to remove"
		}
		summaryLine = fmt.Sprintf("%s, %d %s", summaryLine, c.removed, verb)
	}
	sec.Summary(summaryLine)
	return nil
}

// WriteSnippets writes all generated snippets to cfg.Shell.Dir and deploys
// user snippets from <repoRoot>/shell/, printing a row per snippet under sec.
// It is the building block used by Apply (which adds the header and summary);
// callers that only need the files written can use it directly. sec may be nil.
// With dryRun=true no files are written.
func WriteSnippets(cfg config.Config, dryRun bool, sec *ui.Section) error {
	return writeSnippets(cfg, dryRun, false, sec, &snippetCounts{})
}

func writeSnippets(cfg config.Config, dryRun, summary bool, sec *ui.Section, c *snippetCounts) error {
	dir := fileutil.Expand(cfg.Shell.Dir)

	if !dryRun {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}

	if err := deployUserSnippets(cfg, dir, dryRun, summary, sec, c); err != nil {
		return err
	}

	snippets := map[string]string{
		"010-env.sh":  GenerateEnvSnippet(cfg),
		"020-path.sh": GeneratePathSnippet(cfg),
	}
	plats := platform.Platforms()
	for _, tool := range cfg.Tools {
		for name, shellName := range toolSnippetFiles(tool, plats) {
			snippets[name] = GenerateToolSnippet(tool, shellName)
		}
	}
	if custom, ok, err := GenerateCustomSnippet(cfg.RepoRoot); err != nil {
		return err
	} else if ok {
		snippets["099-custom.sh"] = custom
	}

	names := make([]string, 0, len(snippets))
	for name := range snippets {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		if err := writeSnippet(filepath.Join(dir, name), []byte(snippets[name]), dryRun, summary, sec, c); err != nil {
			return err
		}
	}
	return nil
}

// InsertSourceLine inserts the marker-delimited bootstrapper block into the
// zshrc and bashrc files listed in cfg.Shell, printing a row per rc file under
// sec ("wrote" when the block changed, otherwise "unchanged"). It is the
// building block used by Apply; sec may be nil.
func InsertSourceLine(cfg config.Config, dryRun bool, sec *ui.Section) error {
	return insertSourceLine(cfg, dryRun, false, sec, &snippetCounts{})
}

func insertSourceLine(cfg config.Config, dryRun, summary bool, sec *ui.Section, c *snippetCounts) error {
	for _, rc := range []string{cfg.Shell.Zshrc, cfg.Shell.Bashrc} {
		path := fileutil.Expand(rc)
		bootstrapper := zshBootstrapper
		if rc == cfg.Shell.Bashrc {
			bootstrapper = bashBootstrapper
		}
		changed, err := InsertBlock(path, bootstrapper, dryRun)
		if err != nil {
			return err
		}
		c.add(changed)
		if !summary {
			if changed {
				sec.Status("wrote", "bootstrapper → "+path, dryRun)
			} else {
				sec.Status("unchanged", "bootstrapper → "+path, dryRun)
			}
		}
	}
	return nil
}

// Assembled returns the concatenated content of all snippet files in shell.d,
// sorted by filename.
func Assembled(cfg config.Config) (string, error) {
	dir := fileutil.Expand(cfg.Shell.Dir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}

	var sb strings.Builder
	for _, e := range entries {
		if e.IsDir() || !isSnippetFile(e.Name()) {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return "", err
		}
		sb.Write(data)
	}
	return sb.String(), nil
}

// expectedSnippets returns the set of snippet filenames that the current config
// should produce in shell.d. staleSnippets (and thus both Clean and the cleanup
// baked into Apply) derives its keep-list from this, so the standalone `dots
// shell clean` command and `dots apply` agree on what counts as stale.
func expectedSnippets(cfg config.Config) map[string]bool {
	expected := map[string]bool{
		"010-env.sh":  true,
		"020-path.sh": true,
	}
	// Keep in sync with applyPresets in cmd/dots/commands.go, which writes a
	// per-shell 030-fzf.zsh and 030-fzf.bash into shell.d when the fzf preset
	// is enabled and the shell is managed. Without these entries, cleanup would
	// delete the presets that apply just wrote. (An older 030-fzf.sh is
	// intentionally absent so it is removed on migration.)
	if cfg.Presets.Fzf && cfg.Shell.Managed {
		expected["030-fzf.zsh"] = true
		expected["030-fzf.bash"] = true
	}
	plats := platform.Platforms()
	for _, tool := range cfg.Tools {
		for name := range toolSnippetFiles(tool, plats) {
			expected[name] = true
		}
	}
	if _, ok, _ := GenerateCustomSnippet(cfg.RepoRoot); ok {
		expected["099-custom.sh"] = true
	}
	// User snippets deployed from <repoRoot>/shell/ by deployUserSnippets must
	// never be cleaned; both sides derive the list from userSnippetFiles.
	if names, err := userSnippetFiles(cfg.RepoRoot); err == nil {
		for _, n := range names {
			expected[n] = true
		}
	}
	return expected
}

// staleSnippets returns the sorted names of snippet files present in shell.d
// that the current config no longer expects (e.g. a 050-{tool}.sh left behind
// after a tool's shell directive was removed from dots.toml).
func staleSnippets(cfg config.Config) ([]string, error) {
	dir := fileutil.Expand(cfg.Shell.Dir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	expected := expectedSnippets(cfg)
	var stale []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !isSnippetFile(name) || expected[name] {
			continue
		}
		stale = append(stale, name)
	}
	sort.Strings(stale)
	return stale, nil
}

// Clean removes snippet files from shell.d that are not expected given the
// current config. With dryRun=true no files are removed. It backs the standalone
// `dots shell clean` command; Apply runs the same cleanup as part of every apply.
func Clean(cfg config.Config, dryRun bool) error {
	stale, err := staleSnippets(cfg)
	if err != nil {
		return err
	}
	dir := fileutil.Expand(cfg.Shell.Dir)
	for _, name := range stale {
		if !dryRun {
			if err := os.Remove(filepath.Join(dir, name)); err != nil {
				return err
			}
		}
		ui.StatusLine("removed", name, dryRun)
	}
	if len(stale) == 0 {
		ui.Note("No stale snippets found.")
	}
	return nil
}

// cleanStale removes stale snippets as part of Apply, reporting each removal as
// a row under sec and tallying it in c so the Shell section's summary reflects
// the deletions. With dryRun=true no files are removed.
func cleanStale(cfg config.Config, dryRun bool, sec *ui.Section, c *snippetCounts) error {
	stale, err := staleSnippets(cfg)
	if err != nil {
		return err
	}
	dir := fileutil.Expand(cfg.Shell.Dir)
	for _, name := range stale {
		if !dryRun {
			if err := os.Remove(filepath.Join(dir, name)); err != nil {
				return err
			}
		}
		sec.Status("removed", filepath.Join(dir, name), dryRun)
		c.removed++
	}
	return nil
}

// InsertBlock idempotently inserts content into path using marker-delimited
// replacement. If the file already contains MarkerStart, the block is updated
// in place; otherwise content is appended. Returns true if modified.
func InsertBlock(path, content string, dryRun bool) (bool, error) {
	_, statErr := os.Lstat(path)
	if os.IsNotExist(statErr) {
		if dryRun {
			return true, nil
		}
		// Remove dangling symlink if present.
		if _, lerr := os.Readlink(path); lerr == nil {
			_ = os.Remove(path)
		}
		if err := fileutil.EnsureParent(path); err != nil {
			return false, err
		}
		return true, os.WriteFile(path, []byte(content+"\n"), 0o644)
	}
	if statErr != nil {
		return false, statErr
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	text := string(data)

	if strings.Contains(text, MarkerStart) {
		re := regexp.MustCompile(`(?s)` + regexp.QuoteMeta(MarkerStart) + `.*?` + regexp.QuoteMeta(MarkerEnd))
		// Literal replacement: content contains shell variables ($HOME,
		// $_dots_d, …) that ReplaceAllString would mangle as group references.
		newText := re.ReplaceAllLiteralString(text, content)
		if newText == text {
			return false, nil
		}
		if dryRun {
			return true, nil
		}
		return true, os.WriteFile(path, []byte(newText), 0o644)
	}

	if !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	text += "\n" + content + "\n"
	if dryRun {
		return true, nil
	}
	return true, os.WriteFile(path, []byte(text), 0o644)
}

// RemoveBlock removes the marker-delimited block from path.
// Returns true if the file was modified.
func RemoveBlock(path string, dryRun bool) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	text := string(data)

	if !strings.Contains(text, MarkerStart) {
		return false, nil
	}

	newText := stripMarkerBlock(text)
	if dryRun {
		return true, nil
	}
	return true, os.WriteFile(path, []byte(newText), 0o644)
}

func isSnippetFile(name string) bool {
	if len(name) == 0 || name[0] < '0' || name[0] > '9' {
		return false
	}
	return strings.HasSuffix(name, ".sh") ||
		strings.HasSuffix(name, ".zsh") ||
		strings.HasSuffix(name, ".bash")
}

func sliceContains(slice []string, s string) bool {
	for _, v := range slice {
		if v == s {
			return true
		}
	}
	return false
}

// intersects reports whether any element of a is present in b.
func intersects(a, b []string) bool {
	for _, x := range a {
		if sliceContains(b, x) {
			return true
		}
	}
	return false
}
