package shell

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pkuehne/dots/internal/config"
)

// ── GenerateEnvSnippet ────────────────────────────────────────────────────────

func TestEnvSnippetFormat(t *testing.T) {
	cfg := config.Config{
		Env: config.EnvConfig{
			Vars: map[string]string{"EDITOR": "nvim", "PAGER": "less"},
		},
	}
	result := GenerateEnvSnippet(cfg)
	if !strings.Contains(result, "# Generated by dots") {
		t.Error("missing generated header")
	}
	if !strings.Contains(result, `export EDITOR="nvim"`) {
		t.Error("missing EDITOR export")
	}
	if !strings.Contains(result, `export PAGER="less"`) {
		t.Error("missing PAGER export")
	}
}

func TestEnvSnippetWhenIfTool(t *testing.T) {
	cfg := config.Config{
		Env: config.EnvConfig{
			Vars: map[string]string{},
			When: []config.EnvWhen{
				{Key: "MANPAGER", Value: "bat", IfTool: "bat"},
			},
		},
	}
	result := generateEnvSnippet(cfg, []string{"linux"})
	if !strings.Contains(result, "command -v bat") {
		t.Error("missing if_tool guard")
	}
	if !strings.Contains(result, `MANPAGER="bat"`) {
		t.Error("missing MANPAGER export")
	}
}

func TestEnvSnippetWhenPlatformFilter(t *testing.T) {
	cfg := config.Config{
		Env: config.EnvConfig{
			Vars: map[string]string{},
			When: []config.EnvWhen{
				{Key: "COLORTERM", Value: "truecolor", Only: []string{"linux", "darwin"}},
			},
		},
	}

	result := generateEnvSnippet(cfg, []string{"termux"})
	if strings.Contains(result, "COLORTERM") {
		t.Error("COLORTERM should be filtered out on termux")
	}

	result = generateEnvSnippet(cfg, []string{"linux"})
	if !strings.Contains(result, "COLORTERM") {
		t.Error("COLORTERM should be present on linux")
	}
}

// TestEnvSnippetMultiTagAgreesWithCheck asserts that, for a given tag list, the
// vars emitted by generateEnvSnippet are exactly the [[env.when]] entries whose
// Only intersects that list — the same predicate `dots env check` reports on.
// On WSL the tag list is ["linux","wsl"], so a wsl-only var is emitted there
// but not on a plain linux host.
func TestEnvSnippetMultiTagAgreesWithCheck(t *testing.T) {
	cfg := config.Config{
		Env: config.EnvConfig{
			Vars: map[string]string{},
			When: []config.EnvWhen{
				{Key: "DISPLAY", Value: ":0", Only: []string{"wsl"}},
				{Key: "EDITOR", Value: "vim"},
				{Key: "BROWSER", Value: "safari", Only: []string{"darwin"}},
			},
		},
	}

	// envCheckActive mirrors runEnvCheck's predicate in cmd/dots/commands.go.
	envCheckActive := func(only, plats []string) bool {
		if len(only) == 0 {
			return true
		}
		return intersects(only, plats)
	}

	for _, plats := range [][]string{{"linux"}, {"linux", "wsl"}, {"darwin"}} {
		snippet := generateEnvSnippet(cfg, plats)
		for _, w := range cfg.Env.When {
			present := strings.Contains(snippet, w.Key+"=")
			want := envCheckActive(w.Only, plats)
			if present != want {
				t.Errorf("plats=%v key=%s: snippet present=%v, env check active=%v",
					plats, w.Key, present, want)
			}
		}
	}
}

func TestEnvSnippetHeader(t *testing.T) {
	cfg := config.Config{
		Env: config.EnvConfig{
			Vars: map[string]string{"EDITOR": "vim"},
		},
	}
	result := GenerateEnvSnippet(cfg)
	if !strings.HasPrefix(result, "# Generated by dots") {
		t.Error("snippet must start with generated header")
	}
	if !strings.Contains(result, "Regenerate: dots apply") {
		t.Error("missing regenerate comment")
	}
}

// ── GeneratePathSnippet ───────────────────────────────────────────────────────

func TestPathSnippetDedupes(t *testing.T) {
	t.Setenv("HOME", "/testhome")
	cfg := config.Config{
		Shell:       config.ShellConfig{Path: []string{"~/.local/bin", "~/.cargo/bin", "~/.local/bin"}},
		Tools:       nil,
		ToolsConfig: config.ToolsConfig{BinDir: "~/.local/bin"},
	}
	result := GeneratePathSnippet(cfg)
	count := strings.Count(result, ".local/bin")
	if count != 2 {
		t.Errorf("expected .local/bin to appear 2 times (case pattern + value), got %d\nresult:\n%s", count, result)
	}
}

func TestPathSnippetIncludesToolPaths(t *testing.T) {
	t.Setenv("HOME", "/testhome")
	cfg := config.Config{
		Shell: config.ShellConfig{Path: []string{"~/.local/bin"}},
		Tools: []config.Tool{
			{Name: "go", Shell: config.ToolShell{Path: []string{"~/go/bin"}}},
		},
		ToolsConfig: config.ToolsConfig{BinDir: "~/.local/bin"},
	}
	result := GeneratePathSnippet(cfg)
	if !strings.Contains(result, "go/bin") {
		t.Error("tool path ~/go/bin should appear in path snippet")
	}
}

// ── GenerateToolSnippet ───────────────────────────────────────────────────────

func TestToolSnippetHasGuard(t *testing.T) {
	tool := config.Tool{
		Name:  "delta",
		Shell: config.ToolShell{Env: map[string]string{"DELTA_FEATURES": "line-numbers"}},
	}
	result := GenerateToolSnippet(tool, "zsh")
	if !strings.Contains(result, "command -v delta") {
		t.Error("missing command -v guard")
	}
	if !strings.Contains(result, "|| return") {
		t.Error("missing || return in guard")
	}
	if !strings.Contains(result, `DELTA_FEATURES="line-numbers"`) {
		t.Error("missing DELTA_FEATURES export")
	}
}

func TestToolSnippetGuardFromWhichCheck(t *testing.T) {
	tool := config.Tool{
		Name:  "zoxide",
		Check: "which zoxide",
	}
	result := GenerateToolSnippet(tool, "zsh")
	if !strings.Contains(result, "command -v zoxide") {
		t.Errorf("guard should use binary name from 'which' check, got:\n%s", result)
	}
	if strings.Contains(result, "command -v which") {
		t.Error("guard must not use the literal 'which'")
	}
}

func TestToolSnippetShellSubstitution(t *testing.T) {
	tool := config.Tool{
		Name:  "zoxide",
		Shell: config.ToolShell{Init: `eval "$(zoxide init {shell})"`},
	}
	resultZsh := GenerateToolSnippet(tool, "zsh")
	resultBash := GenerateToolSnippet(tool, "bash")

	if !strings.Contains(resultZsh, "zoxide init zsh") {
		t.Error("zsh snippet should contain 'zoxide init zsh'")
	}
	if !strings.Contains(resultBash, "zoxide init bash") {
		t.Error("bash snippet should contain 'zoxide init bash'")
	}
}

// ── GenerateCustomSnippet ─────────────────────────────────────────────────────

func TestCustomSnippetFromZshrc(t *testing.T) {
	dir := t.TempDir()
	filesDir := filepath.Join(dir, "files")
	if err := os.MkdirAll(filesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(filesDir, ".zshrc"), []byte("alias ll='ls -la'"), 0o644); err != nil {
		t.Fatal(err)
	}

	result, ok, err := GenerateCustomSnippet(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !ok {
		t.Fatal("expected ok=true when files/.zshrc exists")
	}
	if !strings.Contains(result, "alias ll") {
		t.Error("missing alias from files/.zshrc")
	}
	if !strings.Contains(result, "Generated by dots") {
		t.Error("missing generated header in custom snippet")
	}
}

func TestCustomSnippetNoneWithoutZshrc(t *testing.T) {
	dir := t.TempDir()
	_, ok, err := GenerateCustomSnippet(dir)
	if err != nil {
		t.Fatal(err)
	}
	if ok {
		t.Error("expected ok=false when files/.zshrc does not exist")
	}
}

// ── InsertBlock / RemoveBlock ─────────────────────────────────────────────────

func TestInsertBlockCreatesFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "sub", ".zshrc")

	modified, err := InsertBlock(path, zshBootstrapper, false)
	if err != nil {
		t.Fatal(err)
	}
	if !modified {
		t.Error("expected modified=true for new file")
	}
	data, _ := os.ReadFile(path)
	if !strings.Contains(string(data), MarkerStart) {
		t.Error("written file should contain marker start")
	}
}

func TestInsertBlockAppendsToExisting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")
	_ = os.WriteFile(path, []byte("# existing content\n"), 0o644)

	_, err := InsertBlock(path, zshBootstrapper, false)
	if err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(path)
	text := string(data)
	if !strings.Contains(text, "# existing content") {
		t.Error("existing content should be preserved")
	}
	if !strings.Contains(text, MarkerStart) {
		t.Error("marker block should be appended")
	}
}

func TestInsertBlockUpdatesExisting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")
	initial := "# before\n" + zshBootstrapper + "\n# after\n"
	_ = os.WriteFile(path, []byte(initial), 0o644)

	newBlock := MarkerStart + "\n# updated\n" + MarkerEnd
	modified, err := InsertBlock(path, newBlock, false)
	if err != nil {
		t.Fatal(err)
	}
	if !modified {
		t.Error("expected modified=true when block content changed")
	}
	data, _ := os.ReadFile(path)
	text := string(data)
	if !strings.Contains(text, "# updated") {
		t.Error("block should be replaced with new content")
	}
	if !strings.Contains(text, "# before") || !strings.Contains(text, "# after") {
		t.Error("surrounding content should be preserved")
	}
}

func TestInsertBlockIdempotent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")

	_, _ = InsertBlock(path, zshBootstrapper, false)
	_, _ = InsertBlock(path, zshBootstrapper, false)

	data, _ := os.ReadFile(path)
	text := string(data)
	if strings.Count(text, MarkerStart) != 1 {
		t.Errorf("marker should appear exactly once after two inserts, got %d", strings.Count(text, MarkerStart))
	}
}

func TestInsertBlockDryRun(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")

	modified, err := InsertBlock(path, zshBootstrapper, true)
	if err != nil {
		t.Fatal(err)
	}
	if !modified {
		t.Error("dry run should report modified=true")
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Error("dry run must not create file")
	}
}

func TestRemoveBlock(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")
	content := "# before\n" + zshBootstrapper + "\n# after\n"
	_ = os.WriteFile(path, []byte(content), 0o644)

	modified, err := RemoveBlock(path, false)
	if err != nil {
		t.Fatal(err)
	}
	if !modified {
		t.Error("expected modified=true")
	}
	data, _ := os.ReadFile(path)
	text := string(data)
	if strings.Contains(text, MarkerStart) {
		t.Error("marker block should be removed")
	}
	if !strings.Contains(text, "# before") || !strings.Contains(text, "# after") {
		t.Error("surrounding content should be preserved after removal")
	}
}

func TestRemoveBlockNoMarker(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")
	_ = os.WriteFile(path, []byte("# plain file\n"), 0o644)

	modified, err := RemoveBlock(path, false)
	if err != nil {
		t.Fatal(err)
	}
	if modified {
		t.Error("expected modified=false when no marker present")
	}
}

// ── WriteSnippets / Clean / Assembled ────────────────────────────────────────

func TestWriteSnippets(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	cfg := config.Config{
		Shell:       config.ShellConfig{Dir: dir},
		Env:         config.EnvConfig{Vars: map[string]string{"EDITOR": "vim"}},
		Tools: []config.Tool{{
			Name:  "fzf",
			Shell: config.ToolShell{Env: map[string]string{"FZF_DEFAULT_OPTS": "--height 40%"}},
		}},
		ToolsConfig: config.ToolsConfig{BinDir: "~/.local/bin"},
	}

	if err := WriteSnippets(cfg, false); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"010-env.sh", "020-path.sh", "050-fzf.sh"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("expected %s to exist: %v", name, err)
		}
	}
}

// ── toolSnippetFiles / per-tool snippet shapes ───────────────────────────────

func TestWriteSnippetsSkipsToolsWithoutShellConfig(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	cfg := config.Config{
		Shell:       config.ShellConfig{Dir: dir},
		Env:         config.EnvConfig{Vars: map[string]string{}},
		Tools:       []config.Tool{{Name: "jq", Shell: config.ToolShell{}}},
		ToolsConfig: config.ToolsConfig{BinDir: "~/.local/bin"},
	}

	if err := WriteSnippets(cfg, false); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"050-jq.sh", "050-jq.zsh", "050-jq.bash"} {
		if _, err := os.Stat(filepath.Join(dir, name)); !os.IsNotExist(err) {
			t.Errorf("tool without shell config must not get snippet %s", name)
		}
	}
}

func TestWriteSnippetsPerShellVariants(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	cfg := config.Config{
		Shell: config.ShellConfig{Dir: dir},
		Env:   config.EnvConfig{Vars: map[string]string{}},
		Tools: []config.Tool{{
			Name:  "zoxide",
			Shell: config.ToolShell{Init: `eval "$(zoxide init {shell})"`},
		}},
		ToolsConfig: config.ToolsConfig{BinDir: "~/.local/bin"},
	}

	if err := WriteSnippets(cfg, false); err != nil {
		t.Fatal(err)
	}
	for name, want := range map[string]string{
		"050-zoxide.zsh":  "zoxide init zsh",
		"050-zoxide.bash": "zoxide init bash",
	} {
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Errorf("expected per-shell variant %s: %v", name, err)
			continue
		}
		if !strings.Contains(string(data), want) {
			t.Errorf("%s should contain %q, got:\n%s", name, want, data)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "050-zoxide.sh")); !os.IsNotExist(err) {
		t.Error("tool with {shell} init must not also get a .sh snippet")
	}
}

func TestWriteSnippetsSingleSnippetWithoutPlaceholder(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	cfg := config.Config{
		Shell: config.ShellConfig{Dir: dir},
		Env:   config.EnvConfig{Vars: map[string]string{}},
		Tools: []config.Tool{{
			Name:  "direnv",
			Shell: config.ToolShell{Init: `eval "$(direnv hook bash)"`},
		}},
		ToolsConfig: config.ToolsConfig{BinDir: "~/.local/bin"},
	}

	if err := WriteSnippets(cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "050-direnv.sh")); err != nil {
		t.Errorf("expected single 050-direnv.sh: %v", err)
	}
	for _, name := range []string{"050-direnv.zsh", "050-direnv.bash"} {
		if _, err := os.Stat(filepath.Join(dir, name)); !os.IsNotExist(err) {
			t.Errorf("plain-init tool must not get per-shell variant %s", name)
		}
	}
}

func TestCleanToolSnippetNaming(t *testing.T) {
	dir := t.TempDir()
	// The tool's init uses {shell}, so the .zsh/.bash variants are expected
	// and a stale .sh from before the init gained {shell} must be removed.
	for _, name := range []string{"050-zoxide.zsh", "050-zoxide.bash", "050-zoxide.sh"} {
		_ = os.WriteFile(filepath.Join(dir, name), []byte("# snippet"), 0o644)
	}

	cfg := config.Config{
		Shell:    config.ShellConfig{Dir: dir},
		RepoRoot: t.TempDir(),
		Tools: []config.Tool{{
			Name:  "zoxide",
			Shell: config.ToolShell{Init: `eval "$(zoxide init {shell})"`},
		}},
	}
	if err := Clean(cfg, false); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"050-zoxide.zsh", "050-zoxide.bash"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("%s should survive Clean", name)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "050-zoxide.sh")); !os.IsNotExist(err) {
		t.Error("stale 050-zoxide.sh should be removed once init uses {shell}")
	}
}

func TestToolSnippetFilesPlatformScoping(t *testing.T) {
	tool := config.Tool{
		Name:  "mac-thing",
		Only:  []string{"darwin"},
		Shell: config.ToolShell{Init: "eval mac-thing"},
	}
	if got := toolSnippetFiles(tool, []string{"linux", "wsl"}); got != nil {
		t.Errorf("darwin-only tool must yield no snippets on linux+wsl, got: %v", got)
	}
	if got := toolSnippetFiles(tool, []string{"darwin"}); len(got) != 1 {
		t.Errorf("darwin-only tool should yield one snippet on darwin, got: %v", got)
	}
}

func TestWriteSnippetsSkipsPlatformExcludedTool(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	cfg := config.Config{
		Shell: config.ShellConfig{Dir: dir},
		Env:   config.EnvConfig{Vars: map[string]string{}},
		Tools: []config.Tool{{
			Name: "elsewhere",
			// A tag that is never an active platform, so the test is
			// deterministic regardless of the machine it runs on.
			Only:  []string{"some-other-os"},
			Shell: config.ToolShell{Init: "eval elsewhere"},
		}},
		ToolsConfig: config.ToolsConfig{BinDir: "~/.local/bin"},
	}

	if err := WriteSnippets(cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(dir, "050-elsewhere.sh")); !os.IsNotExist(err) {
		t.Error("platform-excluded tool must not get a snippet")
	}
}

func TestCleanRemovesSnippetOfPlatformExcludedTool(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, "050-elsewhere.sh")
	_ = os.WriteFile(stale, []byte("# stale"), 0o644)

	cfg := config.Config{
		Shell:    config.ShellConfig{Dir: dir},
		RepoRoot: t.TempDir(),
		Tools: []config.Tool{{
			Name:  "elsewhere",
			Only:  []string{"some-other-os"},
			Shell: config.ToolShell{Init: "eval elsewhere"},
		}},
	}
	if err := Clean(cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Error("snippet of a platform-excluded tool should be removed")
	}
}

func TestCleanRemovesSnippetOfShellLessTool(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, "050-jq.sh")
	_ = os.WriteFile(stale, []byte("# stale"), 0o644)

	cfg := config.Config{
		Shell:    config.ShellConfig{Dir: dir},
		RepoRoot: t.TempDir(),
		Tools:    []config.Tool{{Name: "jq", Shell: config.ToolShell{}}},
	}
	if err := Clean(cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Error("snippet of a tool without shell config should be removed")
	}
}

func TestWriteSnippetsDryRun(t *testing.T) {
	dir := t.TempDir()
	snippetDir := filepath.Join(dir, "shell.d")
	cfg := config.Config{
		Shell: config.ShellConfig{Dir: snippetDir},
		Env:   config.EnvConfig{Vars: map[string]string{}},
	}

	if err := WriteSnippets(cfg, true); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(snippetDir); !os.IsNotExist(err) {
		t.Error("dry run must not create shell.d directory")
	}
}

func TestCleanRemovesStale(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, "050-oldtool.sh")
	_ = os.WriteFile(stale, []byte("# stale"), 0o644)
	_ = os.WriteFile(filepath.Join(dir, "010-env.sh"), []byte("# env"), 0o644)

	cfg := config.Config{
		Shell:    config.ShellConfig{Dir: dir},
		Tools:    nil,
		RepoRoot: t.TempDir(),
	}
	if err := Clean(cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Error("stale snippet should have been removed")
	}
	if _, err := os.Stat(filepath.Join(dir, "010-env.sh")); err != nil {
		t.Error("010-env.sh should be kept")
	}
}

func TestCleanKeepsFzfPreset(t *testing.T) {
	dir := t.TempDir()
	fzf := filepath.Join(dir, "030-fzf.sh")
	_ = os.WriteFile(fzf, []byte("# fzf preset"), 0o644)

	cfg := config.Config{
		Shell:    config.ShellConfig{Dir: dir},
		RepoRoot: t.TempDir(),
	}
	cfg.Presets.Fzf = true

	if err := Clean(cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(fzf); err != nil {
		t.Error("030-fzf.sh should survive Clean when the fzf preset is enabled")
	}
}

// makeUserSnippetRepo creates a repo root with a shell/ directory containing
// the given name→content files.
func makeUserSnippetRepo(t *testing.T, files map[string]string) string {
	t.Helper()
	repo := t.TempDir()
	shellDir := filepath.Join(repo, "shell")
	if err := os.MkdirAll(shellDir, 0o755); err != nil {
		t.Fatal(err)
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(shellDir, name), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return repo
}

// captureStdout runs fn and returns everything it printed to os.Stdout.
func captureStdout(t *testing.T, fn func()) string {
	t.Helper()
	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	defer func() { os.Stdout = old }()
	fn()
	w.Close()
	data, err := io.ReadAll(r)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func TestWriteSnippetsDeploysUserSnippets(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	repo := makeUserSnippetRepo(t, map[string]string{"035-aliases.sh": "alias ll='ls -la'\n"})
	cfg := config.Config{
		Shell:    config.ShellConfig{Dir: dir},
		Env:      config.EnvConfig{Vars: map[string]string{}},
		RepoRoot: repo,
	}

	out := captureStdout(t, func() {
		if err := WriteSnippets(cfg, false); err != nil {
			t.Error(err)
		}
	})
	if strings.Contains(out, "Warning") {
		t.Errorf("in-range prefix must not warn, got:\n%s", out)
	}
	data, err := os.ReadFile(filepath.Join(dir, "035-aliases.sh"))
	if err != nil {
		t.Fatalf("user snippet should be deployed into shell.d: %v", err)
	}
	if string(data) != "alias ll='ls -la'\n" {
		t.Errorf("deployed content mismatch: %q", data)
	}
}

func TestWriteSnippetsWarnsOnOutOfRangePrefix(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	repo := makeUserSnippetRepo(t, map[string]string{"015-early.sh": "# early\n"})
	cfg := config.Config{
		Shell:    config.ShellConfig{Dir: dir},
		Env:      config.EnvConfig{Vars: map[string]string{}},
		RepoRoot: repo,
	}

	out := captureStdout(t, func() {
		if err := WriteSnippets(cfg, false); err != nil {
			t.Error(err)
		}
	})
	want := "⚠ Warning: 015-early.sh has prefix 15 outside expected ranges (030-049, 080-089, 090+)"
	if !strings.Contains(out, want) {
		t.Errorf("expected warning %q, got:\n%s", want, out)
	}
	// Warned but still deployed, matching the Python behavior.
	if _, err := os.Stat(filepath.Join(dir, "015-early.sh")); err != nil {
		t.Errorf("out-of-range snippet should still be deployed: %v", err)
	}
}

func TestWriteSnippetsSkipsTemplates(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	repo := makeUserSnippetRepo(t, map[string]string{"040-tmpl.sh.j2": "{{ var }}\n"})
	cfg := config.Config{
		Shell:    config.ShellConfig{Dir: dir},
		Env:      config.EnvConfig{Vars: map[string]string{}},
		RepoRoot: repo,
	}

	out := captureStdout(t, func() {
		if err := WriteSnippets(cfg, false); err != nil {
			t.Error(err)
		}
	})
	if !strings.Contains(out, "skipped 040-tmpl.sh.j2 (template — not supported)") {
		t.Errorf("expected visible template skip, got:\n%s", out)
	}
	for _, name := range []string{"040-tmpl.sh.j2", "040-tmpl.sh"} {
		if _, err := os.Stat(filepath.Join(dir, name)); !os.IsNotExist(err) {
			t.Errorf("%s must not be deployed", name)
		}
	}
}

func TestWriteSnippetsUserSnippetsDryRun(t *testing.T) {
	dir := t.TempDir()
	snippetDir := filepath.Join(dir, "shell.d")
	repo := makeUserSnippetRepo(t, map[string]string{"035-aliases.sh": "# aliases\n"})
	cfg := config.Config{
		Shell:    config.ShellConfig{Dir: snippetDir},
		Env:      config.EnvConfig{Vars: map[string]string{}},
		RepoRoot: repo,
	}

	if err := WriteSnippets(cfg, true); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(snippetDir); !os.IsNotExist(err) {
		t.Error("dry run must not create shell.d or deploy user snippets")
	}
}

func TestCleanKeepsUserSnippets(t *testing.T) {
	dir := t.TempDir()
	repo := makeUserSnippetRepo(t, map[string]string{"035-aliases.sh": "# aliases\n"})
	kept := filepath.Join(dir, "035-aliases.sh")
	stale := filepath.Join(dir, "036-gone.sh")
	_ = os.WriteFile(kept, []byte("# aliases\n"), 0o644)
	_ = os.WriteFile(stale, []byte("# no longer in shell/\n"), 0o644)

	cfg := config.Config{
		Shell:    config.ShellConfig{Dir: dir},
		RepoRoot: repo,
	}
	if err := Clean(cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(kept); err != nil {
		t.Error("user snippet deployed from shell/ must survive Clean")
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Error("snippet absent from shell/ should be removed")
	}
}

func TestAssembled(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	_ = os.WriteFile(filepath.Join(dir, "010-env.sh"), []byte("# env\n"), 0o644)
	_ = os.WriteFile(filepath.Join(dir, "020-path.sh"), []byte("# path\n"), 0o644)

	cfg := config.Config{Shell: config.ShellConfig{Dir: dir}}
	result, err := Assembled(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(result, "# env") || !strings.Contains(result, "# path") {
		t.Error("assembled output should contain both snippet contents")
	}
}
