package shell

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pkuehne/dots/internal/config"
)

// ── GenerateEnvSnippet ────────────────────────────────────────────────────────

func TestEnvSnippetFormat(t *testing.T) {
	cfg := config.Config{
		Env: config.EnvConfig{
			Vars: map[string]string{"EDITOR": "nvim", "PAGER": "less"},
		},
	}
	result := GenerateEnvSnippet(cfg)
	if !strings.Contains(result, "# Generated by dots") {
		t.Error("missing generated header")
	}
	if !strings.Contains(result, `export EDITOR="nvim"`) {
		t.Error("missing EDITOR export")
	}
	if !strings.Contains(result, `export PAGER="less"`) {
		t.Error("missing PAGER export")
	}
}

func TestEnvSnippetWhenIfTool(t *testing.T) {
	cfg := config.Config{
		Env: config.EnvConfig{
			Vars: map[string]string{},
			When: []config.EnvWhen{
				{Key: "MANPAGER", Value: "bat", IfTool: "bat"},
			},
		},
	}
	result := generateEnvSnippet(cfg, "linux")
	if !strings.Contains(result, "command -v bat") {
		t.Error("missing if_tool guard")
	}
	if !strings.Contains(result, `MANPAGER="bat"`) {
		t.Error("missing MANPAGER export")
	}
}

func TestEnvSnippetWhenPlatformFilter(t *testing.T) {
	cfg := config.Config{
		Env: config.EnvConfig{
			Vars: map[string]string{},
			When: []config.EnvWhen{
				{Key: "COLORTERM", Value: "truecolor", Only: []string{"linux", "darwin"}},
			},
		},
	}

	result := generateEnvSnippet(cfg, "termux")
	if strings.Contains(result, "COLORTERM") {
		t.Error("COLORTERM should be filtered out on termux")
	}

	result = generateEnvSnippet(cfg, "linux")
	if !strings.Contains(result, "COLORTERM") {
		t.Error("COLORTERM should be present on linux")
	}
}

func TestEnvSnippetHeader(t *testing.T) {
	cfg := config.Config{
		Env: config.EnvConfig{
			Vars: map[string]string{"EDITOR": "vim"},
		},
	}
	result := GenerateEnvSnippet(cfg)
	if !strings.HasPrefix(result, "# Generated by dots") {
		t.Error("snippet must start with generated header")
	}
	if !strings.Contains(result, "Regenerate: dots apply") {
		t.Error("missing regenerate comment")
	}
}

// ── GeneratePathSnippet ───────────────────────────────────────────────────────

func TestPathSnippetDedupes(t *testing.T) {
	t.Setenv("HOME", "/testhome")
	cfg := config.Config{
		Shell:       config.ShellConfig{Path: []string{"~/.local/bin", "~/.cargo/bin", "~/.local/bin"}},
		Tools:       nil,
		ToolsConfig: config.ToolsConfig{BinDir: "~/.local/bin"},
	}
	result := GeneratePathSnippet(cfg)
	count := strings.Count(result, ".local/bin")
	if count != 2 {
		t.Errorf("expected .local/bin to appear 2 times (case pattern + value), got %d\nresult:\n%s", count, result)
	}
}

func TestPathSnippetIncludesToolPaths(t *testing.T) {
	t.Setenv("HOME", "/testhome")
	cfg := config.Config{
		Shell: config.ShellConfig{Path: []string{"~/.local/bin"}},
		Tools: []config.Tool{
			{Name: "go", Shell: config.ToolShell{Path: []string{"~/go/bin"}}},
		},
		ToolsConfig: config.ToolsConfig{BinDir: "~/.local/bin"},
	}
	result := GeneratePathSnippet(cfg)
	if !strings.Contains(result, "go/bin") {
		t.Error("tool path ~/go/bin should appear in path snippet")
	}
}

// ── GenerateToolSnippet ───────────────────────────────────────────────────────

func TestToolSnippetHasGuard(t *testing.T) {
	tool := config.Tool{
		Name:  "delta",
		Shell: config.ToolShell{Env: map[string]string{"DELTA_FEATURES": "line-numbers"}},
	}
	result := GenerateToolSnippet(tool, "zsh")
	if !strings.Contains(result, "command -v delta") {
		t.Error("missing command -v guard")
	}
	if !strings.Contains(result, "|| return") {
		t.Error("missing || return in guard")
	}
	if !strings.Contains(result, `DELTA_FEATURES="line-numbers"`) {
		t.Error("missing DELTA_FEATURES export")
	}
}

func TestToolSnippetShellSubstitution(t *testing.T) {
	tool := config.Tool{
		Name:  "zoxide",
		Shell: config.ToolShell{Init: `eval "$(zoxide init {shell})"`},
	}
	resultZsh := GenerateToolSnippet(tool, "zsh")
	resultBash := GenerateToolSnippet(tool, "bash")

	if !strings.Contains(resultZsh, "zoxide init zsh") {
		t.Error("zsh snippet should contain 'zoxide init zsh'")
	}
	if !strings.Contains(resultBash, "zoxide init bash") {
		t.Error("bash snippet should contain 'zoxide init bash'")
	}
}

// ── GenerateCustomSnippet ─────────────────────────────────────────────────────

func TestCustomSnippetFromZshrc(t *testing.T) {
	dir := t.TempDir()
	filesDir := filepath.Join(dir, "files")
	if err := os.MkdirAll(filesDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(filesDir, ".zshrc"), []byte("alias ll='ls -la'"), 0o644); err != nil {
		t.Fatal(err)
	}

	result, ok, err := GenerateCustomSnippet(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !ok {
		t.Fatal("expected ok=true when files/.zshrc exists")
	}
	if !strings.Contains(result, "alias ll") {
		t.Error("missing alias from files/.zshrc")
	}
	if !strings.Contains(result, "Generated by dots") {
		t.Error("missing generated header in custom snippet")
	}
}

func TestCustomSnippetNoneWithoutZshrc(t *testing.T) {
	dir := t.TempDir()
	_, ok, err := GenerateCustomSnippet(dir)
	if err != nil {
		t.Fatal(err)
	}
	if ok {
		t.Error("expected ok=false when files/.zshrc does not exist")
	}
}

// ── InsertBlock / RemoveBlock ─────────────────────────────────────────────────

func TestInsertBlockCreatesFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "sub", ".zshrc")

	modified, err := InsertBlock(path, zshBootstrapper, false)
	if err != nil {
		t.Fatal(err)
	}
	if !modified {
		t.Error("expected modified=true for new file")
	}
	data, _ := os.ReadFile(path)
	if !strings.Contains(string(data), MarkerStart) {
		t.Error("written file should contain marker start")
	}
}

func TestInsertBlockAppendsToExisting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")
	_ = os.WriteFile(path, []byte("# existing content\n"), 0o644)

	_, err := InsertBlock(path, zshBootstrapper, false)
	if err != nil {
		t.Fatal(err)
	}
	data, _ := os.ReadFile(path)
	text := string(data)
	if !strings.Contains(text, "# existing content") {
		t.Error("existing content should be preserved")
	}
	if !strings.Contains(text, MarkerStart) {
		t.Error("marker block should be appended")
	}
}

func TestInsertBlockUpdatesExisting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")
	initial := "# before\n" + zshBootstrapper + "\n# after\n"
	_ = os.WriteFile(path, []byte(initial), 0o644)

	newBlock := MarkerStart + "\n# updated\n" + MarkerEnd
	modified, err := InsertBlock(path, newBlock, false)
	if err != nil {
		t.Fatal(err)
	}
	if !modified {
		t.Error("expected modified=true when block content changed")
	}
	data, _ := os.ReadFile(path)
	text := string(data)
	if !strings.Contains(text, "# updated") {
		t.Error("block should be replaced with new content")
	}
	if !strings.Contains(text, "# before") || !strings.Contains(text, "# after") {
		t.Error("surrounding content should be preserved")
	}
}

func TestInsertBlockIdempotent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")

	_, _ = InsertBlock(path, zshBootstrapper, false)
	_, _ = InsertBlock(path, zshBootstrapper, false)

	data, _ := os.ReadFile(path)
	text := string(data)
	if strings.Count(text, MarkerStart) != 1 {
		t.Errorf("marker should appear exactly once after two inserts, got %d", strings.Count(text, MarkerStart))
	}
}

func TestInsertBlockDryRun(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")

	modified, err := InsertBlock(path, zshBootstrapper, true)
	if err != nil {
		t.Fatal(err)
	}
	if !modified {
		t.Error("dry run should report modified=true")
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Error("dry run must not create file")
	}
}

func TestRemoveBlock(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")
	content := "# before\n" + zshBootstrapper + "\n# after\n"
	_ = os.WriteFile(path, []byte(content), 0o644)

	modified, err := RemoveBlock(path, false)
	if err != nil {
		t.Fatal(err)
	}
	if !modified {
		t.Error("expected modified=true")
	}
	data, _ := os.ReadFile(path)
	text := string(data)
	if strings.Contains(text, MarkerStart) {
		t.Error("marker block should be removed")
	}
	if !strings.Contains(text, "# before") || !strings.Contains(text, "# after") {
		t.Error("surrounding content should be preserved after removal")
	}
}

func TestRemoveBlockNoMarker(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, ".zshrc")
	_ = os.WriteFile(path, []byte("# plain file\n"), 0o644)

	modified, err := RemoveBlock(path, false)
	if err != nil {
		t.Fatal(err)
	}
	if modified {
		t.Error("expected modified=false when no marker present")
	}
}

// ── WriteSnippets / Clean / Assembled ────────────────────────────────────────

func TestWriteSnippets(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	cfg := config.Config{
		Shell:       config.ShellConfig{Dir: dir},
		Env:         config.EnvConfig{Vars: map[string]string{"EDITOR": "vim"}},
		Tools:       []config.Tool{{Name: "fzf", Shell: config.ToolShell{}}},
		ToolsConfig: config.ToolsConfig{BinDir: "~/.local/bin"},
	}

	if err := WriteSnippets(cfg, false); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"010-env.sh", "020-path.sh", "050-fzf.sh"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("expected %s to exist: %v", name, err)
		}
	}
}

func TestWriteSnippetsDryRun(t *testing.T) {
	dir := t.TempDir()
	snippetDir := filepath.Join(dir, "shell.d")
	cfg := config.Config{
		Shell: config.ShellConfig{Dir: snippetDir},
		Env:   config.EnvConfig{Vars: map[string]string{}},
	}

	if err := WriteSnippets(cfg, true); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(snippetDir); !os.IsNotExist(err) {
		t.Error("dry run must not create shell.d directory")
	}
}

func TestCleanRemovesStale(t *testing.T) {
	dir := t.TempDir()
	stale := filepath.Join(dir, "050-oldtool.sh")
	_ = os.WriteFile(stale, []byte("# stale"), 0o644)
	_ = os.WriteFile(filepath.Join(dir, "010-env.sh"), []byte("# env"), 0o644)

	cfg := config.Config{
		Shell:    config.ShellConfig{Dir: dir},
		Tools:    nil,
		RepoRoot: t.TempDir(),
	}
	if err := Clean(cfg, false); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Error("stale snippet should have been removed")
	}
	if _, err := os.Stat(filepath.Join(dir, "010-env.sh")); err != nil {
		t.Error("010-env.sh should be kept")
	}
}

func TestAssembled(t *testing.T) {
	t.Setenv("HOME", t.TempDir())
	dir := t.TempDir()
	_ = os.WriteFile(filepath.Join(dir, "010-env.sh"), []byte("# env\n"), 0o644)
	_ = os.WriteFile(filepath.Join(dir, "020-path.sh"), []byte("# path\n"), 0o644)

	cfg := config.Config{Shell: config.ShellConfig{Dir: dir}}
	result, err := Assembled(cfg)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(result, "# env") || !strings.Contains(result, "# path") {
		t.Error("assembled output should contain both snippet contents")
	}
}
