"""Tests for SSH config generation and snake_case to PascalCase mapping."""

from unittest.mock import patch

import pytest


def test_snake_to_ssh_keyword(dots):
    """snake_case keys map to SSH PascalCase keywords."""
    assert dots.snake_to_ssh_keyword("identity_file") == "IdentityFile"
    assert dots.snake_to_ssh_keyword("forward_agent") == "ForwardAgent"
    assert dots.snake_to_ssh_keyword("strict_host_key_checking") == "StrictHostKeyChecking"
    assert dots.snake_to_ssh_keyword("proxy_jump") == "ProxyJump"
    assert dots.snake_to_ssh_keyword("user") == "User"
    assert dots.snake_to_ssh_keyword("port") == "Port"


def test_ssh_config_basic(dots):
    """SSH config generates correct Host blocks."""
    config = dots.Config()
    config.ssh_hosts = [
        dots.SSHHost(
            host="*.internal",
            options={"user": "peter", "identity_file": "~/.ssh/id_ed25519"},
        ),
    ]

    with patch.object(dots, "detect_platform", return_value="linux"):
        result = dots.generate_ssh_config(config)

    assert "Host *.internal" in result
    assert "User peter" in result
    assert "IdentityFile ~/.ssh/id_ed25519" in result


def test_ssh_config_platform_filter(dots):
    """SSH host with only filter skips non-matching platform."""
    config = dots.Config()
    config.ssh_hosts = [
        dots.SSHHost(
            host="*.internal",
            only=["linux", "darwin"],
            options={"user": "peter"},
        ),
    ]

    with patch.object(dots, "detect_platform", return_value="termux"):
        result = dots.generate_ssh_config(config)
    assert "Host" not in result or "*.internal" not in result

    with patch.object(dots, "detect_platform", return_value="linux"):
        result = dots.generate_ssh_config(config)
    assert "Host *.internal" in result


def test_ssh_config_bool_values(dots):
    """Boolean SSH options rendered as yes/no."""
    config = dots.Config()
    config.ssh_hosts = [
        dots.SSHHost(
            host="myhost",
            options={"forward_agent": True},
        ),
    ]

    with patch.object(dots, "detect_platform", return_value="linux"):
        result = dots.generate_ssh_config(config)

    assert "ForwardAgent yes" in result


def test_ssh_config_header(dots):
    """Generated SSH config has header."""
    config = dots.Config()
    config.ssh_hosts = []

    result = dots.generate_ssh_config(config)
    assert "Generated by dots" in result


def test_ssh_config_multiple_hosts(dots):
    """Multiple SSH hosts rendered correctly."""
    config = dots.Config()
    config.ssh_hosts = [
        dots.SSHHost(host="host1", options={"user": "alice"}),
        dots.SSHHost(host="host2", options={"user": "bob", "port": 2222}),
    ]

    with patch.object(dots, "detect_platform", return_value="linux"):
        result = dots.generate_ssh_config(config)

    assert "Host host1" in result
    assert "Host host2" in result
    assert "User alice" in result
    assert "User bob" in result
    assert "Port 2222" in result
