"""Tests for SSH config generation and snake_case to PascalCase mapping."""

from unittest.mock import patch

from dots.config import Config, SSHHost
from dots.ssh import generate_ssh_config, snake_to_ssh_keyword


def test_snake_to_ssh_keyword():
    assert snake_to_ssh_keyword("identity_file") == "IdentityFile"
    assert snake_to_ssh_keyword("forward_agent") == "ForwardAgent"
    assert snake_to_ssh_keyword("strict_host_key_checking") == "StrictHostKeyChecking"
    assert snake_to_ssh_keyword("proxy_jump") == "ProxyJump"
    assert snake_to_ssh_keyword("user") == "User"
    assert snake_to_ssh_keyword("port") == "Port"


def test_ssh_config_basic():
    config = Config()
    config.ssh_hosts = [
        SSHHost(
            host="*.internal",
            options={"user": "peter", "identity_file": "~/.ssh/id_ed25519"},
        ),
    ]

    with patch("dots.platform.detect_platform", return_value="linux"):
        result = generate_ssh_config(config)

    assert "Host *.internal" in result
    assert "User peter" in result
    assert "IdentityFile ~/.ssh/id_ed25519" in result


def test_ssh_config_platform_filter():
    config = Config()
    config.ssh_hosts = [
        SSHHost(
            host="*.internal",
            only=["linux", "darwin"],
            options={"user": "peter"},
        ),
    ]

    with patch("dots.platform.detect_platform", return_value="termux"):
        result = generate_ssh_config(config)
    assert "Host" not in result or "*.internal" not in result

    with patch("dots.platform.detect_platform", return_value="linux"):
        result = generate_ssh_config(config)
    assert "Host *.internal" in result


def test_ssh_config_bool_values():
    config = Config()
    config.ssh_hosts = [
        SSHHost(
            host="myhost",
            options={"forward_agent": True},
        ),
    ]

    with patch("dots.platform.detect_platform", return_value="linux"):
        result = generate_ssh_config(config)

    assert "ForwardAgent yes" in result


def test_ssh_config_header():
    config = Config()
    config.ssh_hosts = []

    result = generate_ssh_config(config)
    assert "Generated by dots" in result


def test_ssh_config_multiple_hosts():
    config = Config()
    config.ssh_hosts = [
        SSHHost(host="host1", options={"user": "alice"}),
        SSHHost(host="host2", options={"user": "bob", "port": 2222}),
    ]

    with patch("dots.platform.detect_platform", return_value="linux"):
        result = generate_ssh_config(config)

    assert "Host host1" in result
    assert "Host host2" in result
    assert "User alice" in result
    assert "User bob" in result
    assert "Port 2222" in result
