"""Tests for managed.gitconfig generation."""

from unittest.mock import patch

import pytest


def test_gitconfig_contains_user(dots):
    """managed.gitconfig contains [user] fields."""
    config = dots.Config()
    config.git.name = "Test User"
    config.git.email = "test@example.com"
    config.tools = []

    result = dots.generate_gitconfig(config)
    assert "[user]" in result
    assert "name = Test User" in result
    assert "email = test@example.com" in result


def test_gitconfig_contains_editor(dots):
    """managed.gitconfig contains editor."""
    config = dots.Config()
    config.git.editor = "nvim"
    config.tools = []

    result = dots.generate_gitconfig(config)
    assert "[core]" in result
    assert "editor = nvim" in result


def test_gitconfig_default_branch(dots):
    """managed.gitconfig has defaultBranch."""
    config = dots.Config()
    config.git.default_branch = "main"
    config.tools = []

    result = dots.generate_gitconfig(config)
    assert "defaultBranch = main" in result


def test_gitconfig_pull_rebase(dots):
    """managed.gitconfig respects pull_rebase."""
    config = dots.Config()
    config.git.pull_rebase = True
    config.tools = []

    result = dots.generate_gitconfig(config)
    assert "rebase = true" in result


def test_gitconfig_signing(dots):
    """managed.gitconfig includes signing config."""
    config = dots.Config()
    config.git.name = "Test"
    config.git.email = "test@example.com"
    config.git.sign = True
    config.git.signingkey = "ABCD1234"
    config.tools = []

    result = dots.generate_gitconfig(config)
    assert "[commit]" in result
    assert "gpgsign = true" in result
    assert "signingkey = ABCD1234" in result


def test_gitconfig_delta_when_installed(dots):
    """Delta contribution added when delta is installed."""
    tool = dots.Tool(name="delta")
    tool.git.pager = True
    tool.git.diff = True

    config = dots.Config()
    config.git.name = "Test"
    config.tools = [tool]

    with patch("shutil.which", return_value="/usr/bin/delta"):
        result = dots.generate_gitconfig(config)

    assert "pager = delta" in result
    assert "[diff]" in result
    assert 'tool = delta' in result


def test_gitconfig_delta_omitted_when_missing(dots):
    """Delta contribution omitted when delta not installed."""
    tool = dots.Tool(name="delta")
    tool.git.pager = True
    tool.git.diff = True

    config = dots.Config()
    config.tools = [tool]

    with patch("shutil.which", return_value=None):
        result = dots.generate_gitconfig(config)

    assert "pager = delta" not in result


def test_gitconfig_header(dots):
    """Generated gitconfig has header."""
    config = dots.Config()
    config.tools = []

    result = dots.generate_gitconfig(config)
    assert "Generated by dots" in result
