"""Tests for snippet generation, ordering, guards, and {shell} substitution."""

from unittest.mock import patch

from dots.config import Config, EnvWhen, Tool
from dots.shell import (
    generate_custom_snippet,
    generate_env_snippet,
    generate_path_snippet,
    generate_tool_snippet,
)


def test_env_snippet_format():
    config = Config()
    config.env = {"EDITOR": "nvim", "PAGER": "less"}
    config.env_when = []

    result = generate_env_snippet(config)
    assert "# Generated by dots" in result
    assert 'export EDITOR="nvim"' in result
    assert 'export PAGER="less"' in result


def test_env_snippet_when_if_tool():
    config = Config()
    config.env = {}
    config.env_when = [
        EnvWhen(key="MANPAGER", value="bat", if_tool="bat"),
    ]

    with patch("dots.platform.detect_platform", return_value="linux"):
        result = generate_env_snippet(config)
    assert "command -v bat" in result
    assert 'MANPAGER="bat"' in result


def test_env_snippet_when_platform_filter():
    config = Config()
    config.env = {}
    config.env_when = [
        EnvWhen(key="COLORTERM", value="truecolor", only=["linux", "darwin"]),
    ]

    with patch("dots.platform.detect_platform", return_value="termux"):
        result = generate_env_snippet(config)
    assert "COLORTERM" not in result

    with patch("dots.platform.detect_platform", return_value="linux"):
        result = generate_env_snippet(config)
    assert "COLORTERM" in result


def test_path_snippet_dedupes():
    config = Config()
    config.shell.path = ["~/.local/bin", "~/.cargo/bin", "~/.local/bin"]
    config.tools = []
    config.tools_config.bin_dir = "~/.local/bin"

    result = generate_path_snippet(config)
    # Should only appear once
    assert result.count(".local/bin") == 2  # one in case statement path, one in value


def test_path_snippet_includes_tool_paths():
    tool = Tool(name="go")
    tool.shell.path = ["~/go/bin"]
    config = Config()
    config.shell.path = ["~/.local/bin"]
    config.tools = [tool]
    config.tools_config.bin_dir = "~/.local/bin"

    result = generate_path_snippet(config)
    assert "go/bin" in result


def test_tool_snippet_has_guard():
    tool = Tool(name="delta")
    tool.shell.env = {"DELTA_FEATURES": "line-numbers"}

    result = generate_tool_snippet(tool)
    assert "command -v delta" in result
    assert "|| return" in result
    assert 'DELTA_FEATURES="line-numbers"' in result


def test_tool_snippet_shell_substitution():
    tool = Tool(name="zoxide")
    tool.shell.init = 'eval "$(zoxide init {shell})"'

    result_zsh = generate_tool_snippet(tool, shell_name="zsh")
    result_bash = generate_tool_snippet(tool, shell_name="bash")

    assert "zoxide init zsh" in result_zsh
    assert "zoxide init bash" in result_bash


def test_custom_snippet_from_zshrc(tmp_repo):
    (tmp_repo / "files" / ".zshrc").write_text("alias ll='ls -la'")

    result = generate_custom_snippet(tmp_repo)
    assert result is not None
    assert "alias ll" in result
    assert "Generated by dots" in result


def test_custom_snippet_none_without_zshrc(tmp_repo):
    result = generate_custom_snippet(tmp_repo)
    assert result is None


def test_generated_snippet_header():
    config = Config()
    config.env = {"EDITOR": "vim"}
    config.env_when = []

    result = generate_env_snippet(config)
    assert result.startswith("# Generated by dots")
    assert "Regenerate: dots apply" in result
