"""Tests for managed.gitconfig generation."""

from unittest.mock import patch

from dots.config import Config, Tool
from dots.git import generate_gitconfig


def test_gitconfig_contains_user():
    config = Config()
    config.git.name = "Test User"
    config.git.email = "test@example.com"
    config.tools = []

    result = generate_gitconfig(config)
    assert "[user]" in result
    assert "name = Test User" in result
    assert "email = test@example.com" in result


def test_gitconfig_contains_editor():
    config = Config()
    config.git.editor = "nvim"
    config.tools = []

    result = generate_gitconfig(config)
    assert "[core]" in result
    assert "editor = nvim" in result


def test_gitconfig_default_branch():
    config = Config()
    config.git.default_branch = "main"
    config.tools = []

    result = generate_gitconfig(config)
    assert "defaultBranch = main" in result


def test_gitconfig_pull_rebase():
    config = Config()
    config.git.pull_rebase = True
    config.tools = []

    result = generate_gitconfig(config)
    assert "rebase = true" in result


def test_gitconfig_signing():
    config = Config()
    config.git.name = "Test"
    config.git.email = "test@example.com"
    config.git.sign = True
    config.git.signingkey = "ABCD1234"
    config.tools = []

    result = generate_gitconfig(config)
    assert "[commit]" in result
    assert "gpgsign = true" in result
    assert "signingkey = ABCD1234" in result


def test_gitconfig_delta_when_installed():
    tool = Tool(name="delta")
    tool.git.pager = True
    tool.git.diff = True

    config = Config()
    config.git.name = "Test"
    config.tools = [tool]

    with patch("shutil.which", return_value="/usr/bin/delta"):
        result = generate_gitconfig(config)

    assert "pager = delta" in result
    assert "[diff]" in result
    assert "tool = delta" in result


def test_gitconfig_delta_omitted_when_missing():
    tool = Tool(name="delta")
    tool.git.pager = True
    tool.git.diff = True

    config = Config()
    config.tools = [tool]

    with patch("shutil.which", return_value=None):
        result = generate_gitconfig(config)

    assert "pager = delta" not in result


def test_gitconfig_header():
    config = Config()
    config.tools = []

    result = generate_gitconfig(config)
    assert "Generated by dots" in result
